- Makefile
- README.md
- preprocess.js
Updated the readme.md with the trick that @suskin uses for live refresh of local crossplane docs edits.
> live refresh of local edits of crossplane docs

- index.html
In addition to capitalization of proper nouns, extraneous whitespace was removed.
> Capitalize 'Crossplane' and 'Kubernetes' since they are proper nouns

- Makefile
- README.md
- _config.yml
- _includes/values.inc
Manual updates for rename of `crossplaneio` to `crossplane`.
> Update go mod and refs with crossplane org name

- _layouts/docs.html
This adds some bootstrap dependencies that are needed for nav tabs in markdown docs. See screenshots below and https://github.com/crossplane/crossplane/pull/1514 for more info. I am sure I am committing all sorts of web dev crimes here, but it is a suitable solution for now and only affects the docs layout, not the landing page or others.
> Add bootstrap dependencies for nav tabs in docs

- _config.yml
- _layouts/docs.html
Currently the edit on github link always assumes the document is available on master and also does not include full repo directory path. This updates to link to the specific release branch and also include any directory nesting that is present in the repo but not necessarily rendered in the website url.
This has been tested for both the `master` docs as well as release branches. This fixes for all releases listed on the docs site.
> Fix Edit on Github link for all docs pages

- _includes/values.inc
The current community meeting link is to a section in the README that no
longer exists. This updates it to the correct section.
Fixes https://github.com/crossplane/crossplane/issues/1655
> Update community meeting link

- _layouts/docs.html
Jekyll strips the path from the README page so we must add it back to
make sure the Edit on Github button has the correct link.
Fixes https://github.com/crossplane/crossplane/issues/1658
> Set repopath to docs/README.md if empty

- Makefile
- README.md
run jekyll with  `--incremental` for faster editing using `make run_docs_local_incremental`
> add incremental local docs option to makefile

- LICENSE
- LICENSE-DOCS
- README.md
* Source code is under Apache 2.0 license
* Documentation distributed under CC-BY-4.0
* README clarifies between the two
This is aligned with the footer of crossplane.io:
>  Documentation distributed under CC-BY-4.0.
> Add licenses for this repo

- _includes/values.inc
- _layouts/docs.html
We hardcode v1.0 as latestVersion during v1.1 freeze so that the new
branch will not be the default shown to users visiting the site.
> Force latestVersion to v1.0 during v1.1 freeze

- _layouts/docs.html
We hardcode v1.0 as latestVersion during v1.1 freeze so that the new
branch will not be the default shown to users visiting the site.
> Set latestVersion to v1.0

- _includes/values.inc
- _layouts/docs.html
Updates latest and current docs to match release-1.1 for v1.1.0 release.
See #87 and #88 for context.
Will remain in draft until the `v1.1.0` release is actually live.
> Use release-1.1 branch as latest docs

- _layouts/default.html
This was missed in #94, and updates the site's metadata "description" to match the same headline copy we put into the main page, e.g.: https://github.com/crossplane/crossplane.github.io/pull/94/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L12-R12
I noticed this while troubleshooting the crossplane.io outage today, when pasting crossplane.io into Slack it unfurls the URL and shows the old meta description copy still 😞
> update meta description to new headline copy too

- css/docs.scss
Hi there,
As I browse Crossplane's docs I notice that the font style isn't really uniform. For example, list and tabs are using Helvetica instead of Avenir Roman that is used throughout the rest of the docs.
This PR fixes that super minor issue.
Screenshots:
before:
after:
> use uniform body font for docs

- _includes/values.inc
- _layouts/docs.html
Updates latest and current docs to match release-1.2 for v1.2.0 release.
Will remain in draft until `v1.2.0` is actually live.
> Use release-1.2 branch as latest docs

- _layouts/docs.html
Updates doc pages header to include twitter card.
Fixes #103 
I used the same twitter card that we use on the main page, but we could be a little more creative and populate the description / url with the specific page data. This seems like at least a good start though.
> Add twitter card to docs pages

- _layouts/default.html
- _layouts/docs.html
Updates old documentation pages to include a `noindex` directive to keep them out of search engine results. I verified locally by rendering docs and confirming that old versions do in fact include the `noindex` directive:
Fixes #107
> Do not index old documentation versions

- Makefile
Using the `jekyll/jekyll:latest` tag causes [this issue](https://stackoverflow.com/questions/66113639/jekyll-serve-throws-no-implicit-conversion-of-hash-into-integer-error) due to the use of Ruby 3.
```
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
Source: /srv/jekyll
Destination: /srv/jekyll/_site
Incremental build: enabled
Generating...
done in 25.52 seconds.
jekyll 3.9.0 | Error:  no implicit conversion of Hash into Integer
/usr/gem/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
from /usr/gem/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read'
from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:75:in `proc_version'
from …
```
> Pin Jekyll image tag to 3 for local targets

- OWNERS.md
This PR updates the maintainers list for this https://github.com/crossplane/crossplane.github.io repo.
@plumbis has started contributing significantly to the Crossplane docs recently and will be leading an effort to update and overhaul the experience, of which the initial effort is being tracked in #149.  He has proven domain experience with technical documentation and will be an asset to the quality and velocity of this repository. Thank you for stepping into this position Pete! 🙇‍♂️ 
@connorchan is no longer actively working on the project and is being moved to Emeritus status.  Thank you @connorchan for all of the contributions you've made to this repo and project over the years.  Your efforts are appreciated! 🙇‍♂️
> update OWNERS.md - add plumbis, remove connorchan

- content/docs/_index.md
- themes/crossplane/layouts/_default/redirect.html
Updates the /docs landing page to indicate it should redirect to the latest version.
The redirect is handled by the redirect.html shortcode that is used to link to the external API docs.
> Updates the /docs redirect to always go to latest

- Makefile
Crossplane needs the publish target to commit changes back to this repo, so we restore the Makefile with only that functionality.
> Restore Makefile with only publish target

- themes/crossplane/layouts/_default/list.html
- themes/crossplane/layouts/_default/single.html
In the scramble to fix the deployment on Friday a template was modified that causes the alert on pages that aren't $latest to not show up. 
This passes the correct context to the partial page that checks the versions and renders the alert as necessary.
> Fix alert box for older versions

- themes/crossplane/layouts/shortcodes/hint.html
- themes/crossplane/layouts/shortcodes/hover.html
- themes/crossplane/layouts/shortcodes/include.html
Shortcodes for multiple functionality placed as holders for the upcoming design and to make it easier to contribute Upbound documentation to Community docs.
> add placeholder shortcodes 

- themes/crossplane/layouts/shortcodes/include.html
Resolves #170 
Attempting to start hugo with an `include` shortcode for a file that doesn't exist (or incorrect path) will generate an error message during build:
```shell
Start building sites …
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
ERROR 2022/10/20 16:22:51 Couldn't find include file child_page.md in page "/Users/plumbis/git/docs/content/contributing.md:391:1"
Error: Error building site: logged 1 error(s)
```
> ensure include file exists or error

- themes/crossplane/layouts/partials/docs/version-alert.html
In #165 we changed the version param from a float to a string. The check for printing an alert that the current page isn't the latest release wasn't changed to cover strings instead of floats.
> Corrects the check to see if this doc is for the latest version. 

- themes/crossplane/static/css/404.css
- themes/crossplane/static/css/community.css
- themes/crossplane/static/css/docs.css
- themes/crossplane/static/css/index.css
- themes/crossplane/static/css/main.css
Uses prettier to format CSS to be more friendly for developers to
interact with.
Fixes the latest tag overlapping with the version in the selector.
> Format CSS styles and fix latest version overlap

- themes/geekboot/assets/scss/_sidebar.scss
- themes/geekboot/layouts/partials/docs-sidebar.html
This pre-adds the `collapsed` class to left-nav elements and updates the icon styles to key on the collapsed element instead of the checkbox state.
Fixes: #220 
> Collapse icon fix #220

- content/master
Drops symlink to master directory so that the directory itself can be re-inserted on next merge.
> Drop symlink to master directory

- themes/geekboot/assets/scss/_content.scss
- themes/geekboot/assets/scss/bootstrap/_variables.scss
- themes/geekboot/assets/scss/docs.scss
Fixes #230
Updates the headings to use [Bootstrap RFS](https://getbootstrap.com/docs/5.2/getting-started/rfs/) so heading sizes are responsive based on window size.
This also makes the heading sizes have expected relative sizes, independent of location in the page. 
> Fix heading font sizes

- themes/geekboot/assets/scss/_content.scss
This fixes a regression caused by #230.
The accordion feature (`{{<expand ... >}}`) uses a heading for the title. This creates extra top margin
This removes that margin for heading elements that are also accordion features.
> Accordion header padding fix

- themes/geekboot/assets/scss/_content.scss
With the current style if an inline command (i.e., single tick like `this`) is also a link there is no styling to indicate this.
Today:
This updates the styling to change the color and add an underline to the link inside the inline command.
> Update Styles to clearly indicate links in command text

- themes/geekboot/assets/scss/_survey.scss
- themes/geekboot/assets/scss/docs.scss
- themes/geekboot/layouts/_default/list.html
- themes/geekboot/layouts/partials/survey.html
Removes styles and pages related to the survey banner. 
Resolves #251.
Results for the survey are tracked in #252.
> Removes links to docs user survey

- README.md
[Browserstack ](https://www.browserstack.com/open-source) provides a number of automated UI regression and browser compatibility tests for websites.
Browserstack provides free accounts for OSS projects but requires acknowledgment of their support in the project README and uses this to line verify project ownership.
> Add Browserstack notice for OSS project sponsorship

- config.yaml
- themes/geekboot/layouts/partials/docs-navbar.html
Looks for the Netlify `CONTEXT` environmental variable and generates a small banner at the top of the page when it's `deploy-preview`.
The banner **isn't** set for local development or production builds.
This change requires modifying the [Hugo security settings](https://gohugo.io/about/security-model/#security-policy) to allow access to the envvars.
Preview:
Resolves #248
> Add notice for deploy-previews. 

- .github/ISSUE_TEMPLATE/new_release.md
- Makefile
Related to Crossplane issue [#3461](https://github.com/crossplane/crossplane/issues/3461).
This creates a new issue template for Crossplane releases and removes the publish directive from the local Makefile.
> Changes for moving docs source of truth

- themes/geekboot/layouts/partials/docs-navbar.html
Updates the link to `Documentation` to be relative based on where hugo is being run. This makes the link correct for local development (localhost), build previews (netlify) and prod (docs.crossplane.io)
> Make navbar Documentation Link relative to environment

- .gitignore
When running [Netlify CLI](https://docs.netlify.com/cli/get-started/) locally to test the netlify build it creates a `.netlify` folder. This should never be added to the repo.
> add netlify dev files to gitignore

- themes/geekboot/layouts/partials/scripts.html
- themes/geekboot/layouts/partials/search-button.html
The Algolia search box is created by the Algolia JS block based on a provided div `id`.
Today the script that does this is in the footer of the page, making it the last thing rendered. The problem is that it causes a content shift, moving the nav down to inject the box.
This puts the JS immediately after the div. The JS will be loaded before the rest of the page and prevents the content shift.
> Moves the search box JS from end of page to search div

- config.yaml
- themes/geekboot/layouts/partials/scripts.html
- themes/geekboot/layouts/partials/search-button.html
Fixes two issues:
* Oversight on my part that #262 implies a `docs` param. This happened because it was pulled from the larger #254 PR and I missed the update to config.yml
* The script that loads the search box wasn't moved into the header in #259. My local previews worked because of caching. 
> Fix search and version drop down

- README.md
I was making a fresh clone of this repo when I saw that it was forked from crossplane.github.io and stated in the README that it was both the website and docs. This surprised me, since crossplane/docs seemed like a misleading place to find the website.
I then learned that the website is in fact a separate repo, at https://github.com/crossplane/website
> Clarify that this repo is only the docs

- themes/geekboot/layouts/partials/docs-sidebar.html
This PR simplifies the code that builds the left-hand navbar.  This also will support the future addition of the Knowledge Base and Contributor's Guide links. 
> Rework sidebar. Simplify code and enable for support for KB and contrib

- OWNERS.md
Adds @turkenh and @muvaf as maintainers.
Mirrors the maintainer list from crossplane/crossplane.
> Mirror crossplane/crossplane OWNERS.md

- netlify.toml
#300 changed the build command and has an extra `&&` causing the command to fail.
This wasn't hit in the deploy preview because they use different command lines.
> Remove extra &&

- OWNERS.md
@jeanduplessis  has provided multiple docs reviews and has extensive frontend experience that I'm lacking. Jean is also active in the Crossplane/Crossplane project.
> Add @jeanduplessis as a maintainer

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/content.md
- .github/ISSUE_TEMPLATE/new_release.md
- .github/ISSUE_TEMPLATE/website.md
Expands the issue release template with directions regarding EOL versions.
Creates new templates for docs bugs, website issues and content requests.
> Add more issue templates

- content/contribute/code-style-guide.md
- themes/geekboot/layouts/shortcodes/editCode.html
This PR creates a new shortcode called `editCode`. Authors can add `$$` around a word or line to make it editable in the code block. 
This works by using a regex for `\$\$(.*)\$\$` and replacing it with `<span contentEditable="true">`. The HTML [contenteditable](https://www.w3schools.com/tags/att_global_contenteditable.asp) tag does the work. 
A live example and docs are in the deploy preview. 
https://deploy-preview-311--crossplane.netlify.app/contribute/code-style-guide/#editable-fields
> Enable optional line/field editing in code examples

- themes/geekboot/layouts/partials/header.html
- themes/geekboot/layouts/partials/master-version-alert.html
- themes/geekboot/layouts/partials/old-version-alert.html
This PR adds metadata to each page of when the page was last modified in Git. 
This will be used to influence Algolia search results to favor more recently changed files (among other parameters including version and content).
This is related to #315
> Add last changed metadata to pages for search

- content/master/software/_index.md
- content/master/software/upgrade.md
- content/v1.11/software/_index.md
- content/v1.11/software/upgrade.md
While investigating #315 I noticed there are links to "https://docs.crossplane.io/v1.11/software/HAHAHUGOSHORTCODE-s0-HBHB". 
This turns out to be an issue in Hugo with using the table of contents short code for things that are tied to a shortcode (in our case `{{<ref>}}`). 
This updates the links and sets the Upgrade  guide to `draft` since it hasn't been written yet. 
> Fixes links that generate bad links due to Hugo limitation

- content/master/concepts/providers.md
- content/v1.11/concepts/providers.md
A markdown link is breaking across lines due to line wrap and is generating a link to `"managed-resources"` (with quotes).
This changes those links to use `ref` shortcode to catch broken links in the future. 
> corrects link to managed-resources that has incorrect quotes

- README.md
This PR updates the README.md in this docs repo to point to the correct URL for crossplane docs contribution guide - it was missing the docs subdomain.
This PR contains 2 commits, one to make the small URL/link change, and another to wrap the lines.
> Update link to docs contributing guide in README.md  

- content/v1.11/getting-started/provider-azure.md
Adds a link to Helm that is missing. 
Removes the `{{<include>}}` shortcode that was incorrectly commented out. 
Resolves #341 
> fix helm link, remove include

- content/v1.11/concepts/composition.md
- content/v1.11/concepts/managed-resources.md
- content/v1.11/concepts/providers.md
Currently, some links on the docs site lead to 404 as quotes are treated as parts of the URL (for example in [managed-resources](https://docs.crossplane.io/v1.11/concepts/managed-resources/) page, XRM link leads to `https://docs.crossplane.io/v1.11/concepts/managed-resources/"terminology"` which doesn't exist). This PR attempts to fix this issue.
If you want, I can offer my help with implementing CI workflow with `mdox` for docs formatting and link validation (similar to what was implemented in prometheus-operator at https://github.com/prometheus-operator/prometheus-operator/blob/main/Makefile#L324-L327)
> content/v.1.11: do not quote links as it leads to 404s

- content/master/concepts/packages.md
- content/v1.11/concepts/packages.md
Adds a warning in the package documentation that the ControllerConfig API is now deprecated.
> Add warning that ControllerConfig is deprecated

- content/knowledge-base/guides/composition-functions.md
Updates docs to state that the xfn function runner is deployed as a sidecar container rather than a pod.
> Correct xfn sidercar to container rather than pod

- content/contribute/infrastructure.md
- content/knowledge-base/guides/composition-functions.md
- content/knowledge-base/guides/troubleshoot.md
- content/knowledge-base/integrations/vault-as-secret-store.md
- content/master/software/install.md
- content/v1.10/contributing/adding_external_secret_store_support.md
- content/v1.10/contributing/docs.md
- content/v1.10/guides/vault-as-secret-store.md
- content/v1.10/reference/troubleshoot.md
- content/v1.11/getting-started/introduction.md
- content/v1.11/getting-started/provider-aws-part-2.md
- content/v1.11/getting-started/provider-aws-part-3.md
- content/v1.11/getting-started/provider-aws.md
- content/v1.11/software/install.md
- content/v1.9/contributing/adding_external_secret_store_support.md
- themes/geekboot/assets/scss/_code-theme-base.scss
The first commit updates the CSS to apply a `$` character before the first line of a ` ```shell ` codefence.
The other, larger, commit scrubs existing shell code fences to ensure each codefence executes a single command. 
Resolves #317 
> Adds a $ prompt before the first command in each shell output

- content/v1.11/getting-started/provider-gcp.md
Installing upbound.io gcp provider v0.15.0 causes RBAC issues on GKE. I think the version should be updated in the documentation, or advise to install the latest version more clearly.
> Update version of upbound gcp provider in documentation

- content/v1.10/reference/install.md
- content/v1.9/reference/install.md
- themes/geekboot/assets/scss/_code-theme-base.scss
- themes/geekboot/layouts/partials/analytics.html
- themes/geekboot/layouts/partials/hubspot.html
Google Search Console reports issues with mobility due to text size and elements too close together.
This PR removes the unused Hubspot analytics that contains too small text and puts additional space between code box line numbers when the viewport is a mobile device.
Two pages have outputs that create large horizontal scrolls. This places their content into responsive tables to prevent other mobile issues.
> Fix mobility issues reported by Google Console

- content/master/getting-started/provider-azure.md
- content/master/getting-started/provider-gcp.md
- content/v1.11/getting-started/provider-gcp.md
Fixes a broken helm link in the GCP quickstart.
Removes broken crossplane installation instructions.
> Fix broken links and includes

- themes/geekboot/assets/scss/_sidebar.scss
- themes/geekboot/layouts/partials/docs-sidebar.html
Resolves #297
makes the entire left-nav menu item clickable instead of only the word. 
> Make entire sidebar menu clickable

- content/knowledge-base/guides/composition-revisions-example.md
- themes/geekboot/layouts/partials/feature-state-alert.html
@ezgidemirel noticed I accidentally dropped her Composition Revision Examples guide after the v1.11 reorg. This restores the page (ignoring vale warnings since this page hasn't been edited for vale yet).
This also fixes an error where an extra `}}` is printed in alpha/beta feature flag warning. 
> Restore comp revision example guide

- content/knowledge-base/guides/composition-functions.md
The composition functions install command was missing a new line continuation and was not working.
> Fixing composition functions install command

- themes/geekboot/assets/scss/_code-theme-base.scss
- themes/geekboot/layouts/partials/scripts.html
- themes/geekboot/layouts/shortcodes/editCode.html
Resolves #329 
When clicking on an editable field, if the contents are the placeholder text, the contents are cleared.
If you click away and the contents are blank the placeholder text is restored.
To support this the placeholder text is added as a `data-` element in the span. 
Demo: https://deploy-preview-374--crossplane.netlify.app/v1.11/getting-started/provider-aws/#generate-an-aws-key-pair-file
> Script to clear or reset span contents for editable elements

- content/master/getting-started/provider-azure.md
- content/v1.11/getting-started/provider-azure.md
This PR simply bumps the version of provider-azure used in the Azure getting started guide to the most recent version of v0.29.0.
Partially fixes #383, just for provider-azure, since that's the one causing us the most problems and has an obvious quick solution - we've seen a lot of folks stumbling over this.
I have taken a full pass through the current [Azure getting started guide](https://docs.crossplane.io/v1.11/getting-started/provider-azure/) and verified all the functionality still works.
Some highlights from the testing:
Installed the `provider-azure:v0.29.0` package and it is healthy:
```console
❯ kubectl get pkg
NAME                                                INSTALLED   HEALTHY   PACKAGE                                          AGE …
```
> Update Azure getting started guide to use provider-azure:v0.29.0

- content/master/concepts/composition.md
Documenting Composition Validation introduced in https://github.com/crossplane/crossplane/pull/3756, https://github.com/crossplane/crossplane/pull/3921 and https://github.com/crossplane/crossplane/pull/3937.
> docs: composition validation

- content/master/concepts/composition.md
- content/v1.11/concepts/composition.md
Fixes #394.
Added both to master and 1.11, given that it was introduced for 1.11 afaict.
Also adds `ToSha*` convert transforms to the list of available values and reorder already present examples.
> docs: document ToJson convert transform option

- utils/vale/styles/alex/Ablist.yml
The original definition
(https://github.com/retextjs/retext-equality/blob/main/rules.md) of this rule shows the context to be specific to how people with disabilities are addressed.
Since we are not discussing humans we can remove the check.
@jeanduplessis put it well in [#402](https://github.com/crossplane/docs/pull/402#issuecomment-1512548507)
> If I take a step back and look at "acceptable" language in engineering, I don't see folks objecting to enable/disable as a language choice in the same way that things like master and whitelist/blacklist are objected to. The rule in Vale also clearly speaks to the subject being a person, not an inanimate/abstract concept.
> 
> It is highly unlikely that we would be talking about people in the context of a disability in our technical …
> Remove 'disabled'

- utils/vale/.vale.ini
- utils/vale/styles/Crossplane/spelling-exceptions.txt
- utils/vale/styles/Microsoft/Terms.yml
- utils/vale/styles/gitlab/Wordy.yml
- utils/vale/styles/write-good/Weasel.yml
PR #407 and #402 exposed a few Vale rules that needed to be adjusted.
* Turns off "prefer `cloud` over `the cloud`". This is a problem in marketing not for our docs. "The cloud provider" is a common phrase in Crossplane.
* Turns off Google and Microsoft Latin checks, which are duplicates of the Gitlab Latin checks (1/3rd the errors for using `i.e.`!) 
* Turns off Google check for `will`. This is covered by Gitlab.FutureTense (50% fewer errors!)
* Promotes Gitlab.Wordy to warning to catch the use of `please`. Previously it was a `suggestion`. Changing our warning level to `suggestion` will be way too noisy. 
* Adds the word `Enum` to our custom word list
* Removes duplicate words `Alternatively` and `Simply` which are covered by other checks.
> Update Vale rules based on PR #407 and #402

- .github/ISSUE_TEMPLATE/new_release.md
When cutting a new version we need to manually trigger an algolia search reindex so search results don't include the recently removed version.
> Add a step to manually reindex search after publishing a version

- content/contribute/vale.md
Adds information to the Vale section of the docs contrib guide to call out:
1.) We're in the process of editing content to pass vale and errors in old content are okay, but we want vale to pass for new content.
2.) Warnings == Errors
> Add more information about vale error and warning policy

- themes/geekboot/layouts/404.html
We delete versions of docs that are EOL'd. The down side is that old bookmarks or bad search results (i.e. #422) can lead to a Netlify default 404 page that leaves you stranded. 
This creates a 404 that provides the search box and lists the available sections.
Resolves #416
> create a custom 404 to list sections of available content

- themes/geekboot/assets/scss/_content.scss
- themes/geekboot/layouts/partials/ga-tag.html
- themes/geekboot/layouts/partials/single-list.html
This adds support for a new front matter element `ga: <version>`. 
This doesn't validate the version tag but will print a "GA version: <>" on the page to indicate when a feature went GA.
Resolves #417 
An example of usage is here, under the version drop down. 
https://deploy-preview-425--crossplane.netlify.app/v1.12/concepts/providers/
**Note** The edit to `/content/v1.12/concepts/providers.md` needs to be reverted before merging. 
> Support dynamic GA tag

- .github/ISSUE_TEMPLATE/new_release.md
- netlify.toml
- netlify_build.sh
- themes/geekboot/layouts/_default/sitemap.xml
- themes/geekboot/layouts/partials/header.html
- themes/geekboot/layouts/partials/single-list.html
- themes/geekboot/layouts/partials/version-dropdown-menu.html
Fixes #422
This required a bit of work to make it future proof-
* Generate a `/latest` directory of content at build time. This replaces the current method of 302 redirects. This is needed to have actual content Google can index on instead of redirects
* Custom generate the sitemap.xml to only list the content in /latest + KB and Contrib guides. No older pages should be indexed.
* Fixing canonical URLs point to /latest if the older page exists in the /latest version
* Dropdown menu fixes related to version checking. 
* Moving the Netlify build commands into a stand alone bash script instead of one long command 
On the Netlify admin panel I also enabled a plugin to submit any updates to the sitemap.xml on production build, to help improve the speed of search updates 
Signed-off-by: Pete …
> Search index only for /latest

- netlify_build.sh
The fix in #422 uses the netlify dynamic URL, which changes all the links on the site. This forces the links to use docs.crossplane.io
> Use proper URL for production builds

- content/knowledge-base/guides/troubleshoot.md
This adds troubleshooting steps for compositions, XRDs, and providers with examples. These were originally written for the  [Crossplane on EKS repository](https://github.com/awslabs/crossplane-on-eks/blob/main/doc/debugging.md), but steps outlined in the documents apply to non-AWS resources as well. 
The original doc has a mermaid diagram to help the readers visualize the concept, but it looks like Hugo doesn't support it natively.
CC @ytsarev
> add a section for troubleshooting composition

- postcss.config.js
We found an issue today where Safari renders the top navbar incorrectly. 
After a bunch of testing it seems this has never worked properly and is possibly related to the use of media queries with Safari. 
The fix was to update the [LightningCSS](https://lightningcss.dev/) configuration to transpile our CSS to ensure support for common browsers (including Safari).
I've verified this looks right in Safari 14.1, 15.6 and 16.3. Chrome 112 and Firefox 112.
> Fix Safari Styling

- content/master/getting-started/introduction.md
- content/v1.11/getting-started/introduction.md
- content/v1.12/getting-started/introduction.md
- utils/vale/styles/Google/Headings.yml
- utils/vale/styles/write-good/TooWordy.yml
As reported in #427, in the Intro to Crossplane chapter there are a number of locations where XRD and CRD are mixed up.
This fixes that and makes a few minor vale updates.
> Fix XRD/CRD mixup

- content/master/software/install.md
- content/v1.11/software/install.md
- content/v1.12/software/install.md
[c/c issue #4049](https://github.com/crossplane/crossplane/issues/4049) discusses the fact docs currently list super old versions of k8s as supported. The decision there was we should track to the currently supported versions in the k8s community. 
This adds a notice that we track to the community.
> add information about supported k8s versions

- content/master/software/install.md
- content/v1.11/software/install.md
- content/v1.12/software/install.md
Makes a change to PR #437 to stay "actively supported k8s version" instead of a specific release so we don't have to keep it updated.
> Be less specific about supported k8s version

- content/master/getting-started/provider-gcp-part-2.md
- content/master/getting-started/provider-gcp-part-3.md
- content/master/getting-started/provider-gcp.md
- content/v1.11/getting-started/provider-gcp-part-3.md
- content/v1.12/getting-started/provider-gcp-part-2.md
- content/v1.12/getting-started/provider-gcp-part-3.md
- content/v1.12/getting-started/provider-gcp.md
GCP guides were not synced in /master and the v1.11 wasn't carried over to v1.12
This copies the (correct) v1.11 guides to /master and /v1.12 folders.
> Updates GCP quickstarts to match v1.11's three-part guide

- content/master/getting-started/provider-aws-part-3.md
- content/v1.11/getting-started/provider-aws-part-3.md
- content/v1.12/getting-started/provider-aws-part-3.md
QS incorrectly states you can use UXP for creating packages. Should be `up` CLI. 
Resolves #331
> Corrects statement about UXP to Up CLI. Resolves #331

- content/knowledge-base/integrations/vault-as-secret-store.md
Plugin support has been released and we no longer need development builds for that.
> Update notice for ESS plugin support

- netlify.toml
A few pages for the v1.9 docs are in existing press about Crossplane that direct to pages that are no longer live.
This creates Netlify redirects for those pages.
> Add redirects for top 404 pages

- content/master/concepts/composition.md
- content/v1.12/concepts/composition.md
This adds an example of claiming existing composite resources. Currently, the documentation instructs readers to update the `spec.resourceRef` field but does not give an example.
This PR does not introduce new vale errors or warnings.
> add an example for claiming existing xr

- themes/geekboot/layouts/partials/sidebar/roadmap.html
Similar to https://github.com/crossplane/crossplane/pull/4179, this PR updates all links in the docs repo to the public roadmap so that the info panel is also shown upon landing on the roadmap. All the important expectation setting details are included in that info panel, which GitHub does not display by default, so we would like to increase the chances that users will see it.
Compare:
with info panel: https://github.com/orgs/crossplane/projects/20/views/3?pane=info
without info panel: https://github.com/orgs/crossplane/projects/20/views/3
I've tested the deploy preview and the link works OK ✅
> Update roadmap links to include info panel

- content/knowledge-base/guides/composition-functions.md
As the followup of https://github.com/crossplane/crossplane/issues/2772
this PR adds a few more details on possible usage of connection details
inside a composition function.
> More details on possible usage of connection details inside composition function

- content/master/getting-started/provider-aws.md
- content/v1.12/getting-started/provider-aws.md
A command in the AWS quickstart didn't limit the copy lines and copies the command and output. 
Resolves #464.
> Fix copy button to only copy the command and not the output

- content/master/concepts/packages.md
- content/v1.10/concepts/packages.md
- content/v1.11/concepts/packages.md
- content/v1.12/concepts/packages.md
Suggesting to use image digests instead of tags for security reasons.
This is due to the underlying implementation of go-containerregistry we use to pull images, which is not able to validate digests if not provided, see the [code](https://github.com/google/go-containerregistry/blob/5fe7f2e11795fcfd5a7c7d3a550c4e668a9a9789/pkg/v1/remote/fetcher.go#L172-L180) for more details.
I didn't specifically point out the details, as I feel it's kind of well known in the field that specifying digests is a good practice and a requirement in highly regulated and security-aware environments.
> docs: suggest using image digests for security reasons

- themes/geekboot/layouts/partials/social.html
Fix issue where version number isn't displayed properly in opengraph previews
> fix OG title generation for latest version

- themes/geekboot/layouts/partials/google-analytics.html
This removes the older google analytics tag and leaves the existing GA4 tag.
> Remove legacy google analytics tag

- content/knowledge-base/guides/release-cycle.md
As a follow-up here in the docs from https://github.com/crossplane/crossplane/pull/4211, this PR clarifies that the release dates are approximate and provides reasoning why.
> Clarify that release dates are approximate

- .github/workflows/weekly-link-checker.yml
- utils/htmltest/.htmltest.yml
External links are not checked in CI since it would dramatically increase the test time. 
Inspired by #486, this adds a weekly github action to check external links. The time selected doesn't matter, but Monday morning seems good since any failures would be top of inbox to fix.
> Weekly scheduled external link checking

- content/knowledge-base/guides/troubleshoot.md
- content/master/getting-started/provider-aws-part-2.md
- content/master/getting-started/provider-aws-part-3.md
- content/master/getting-started/provider-aws.md
- content/master/getting-started/provider-azure-part-2.md
- content/master/getting-started/provider-azure-part-3.md
- content/master/getting-started/provider-azure.md
- content/master/getting-started/provider-gcp-part-2.md
- content/master/getting-started/provider-gcp-part-3.md
- content/master/getting-started/provider-gcp.md
- content/v1.10/contributing/observability_developer_guide.md
- content/v1.11/getting-started/provider-aws-part-2.md
- content/v1.11/getting-started/provider-aws-part-3.md
- content/v1.11/getting-started/provider-aws.md
- content/v1.11/getting-started/provider-azure-part-2.md
- content/v1.11/getting-started/provider-azure-part-3.md
- content/v1.11/getting-started/provider-azure.md
- content/v1.11/getting-started/provider-gcp-part-2.md
- content/v1.11/getting-started/provider-gcp-part-3.md
- content/v1.11/getting-started/provider-gcp.md
- content/v1.12/getting-started/provider-aws-part-2.md
- content/v1.12/getting-started/provider-aws.md
- content/v1.12/getting-started/provider-azure-part-2.md
- content/v1.12/getting-started/provider-azure-part-3.md
- content/v1.12/getting-started/provider-azure.md
- content/v1.12/getting-started/provider-gcp-part-2.md
- content/v1.12/getting-started/provider-gcp-part-3.md
- content/v1.12/getting-started/provider-gcp.md
Inspired by #486, I crawled all the external links that were ignored by `htmltest` and updated all broken links to correct references.
Managing this in the future is tracked by #488 .
> Fix broken external links

- content/master/concepts/composition.md
- content/v1.10/reference/composition.md
- content/v1.11/concepts/composition.md
- content/v1.12/concepts/composition.md
This PR attempts to clarify the nuances/specifics that are necessary to correctly specify the connection details that will be aggregated from composed resources and published for a claim.
This wording was put together in our latest FAQ blog post, so I wanted to bring the docs closer in line to what we felt worked in that post: https://blog.crossplane.io/faq-2-claim-connection-details/
Most of the changes are just rewordings and clarifications, e.g. to point to specific field paths, but there is 1 line I found in my testing that appears to be incorrect in our current docs:
1. The claim and XR must both specify a `writeConnectionSecretToRef`.
I believe this is inaccurate because XR/XRDs do not have a `writeConnectionSecretToRef` field.  Instead, a Composition has a …
> Clarify the specifics of connection details in compositions

- themes/geekboot/layouts/partials/google-analytics.html
updates the google analytics tag for the new google analytics 4 requirements.
> Update tags for new GA version

- content/master/concepts/composition-functions.md
Resolves https://github.com/crossplane/docs/issues/502
Clarifies content of `desired.resources` and when resources produced by function pipeline may be present. It is now less likely that someone thinks resources produced by a function pipeline is also copied from `observed` to `desired` during _bootstrapping_ of initial desired state.
- I think it is good actually use the word _composite_, as it refers to the `composite` field within `desired`
- Clarifies that _existing composed resources_  are produced from the `resources` array (same origin as _new_ and _modified_)
- Explicitly states that initial desired state does not contain resources produced by the function pipeline
- And that the desired resources output of a function is passed as input to the next pipeline function
> docs:  clarify content of desired resources in composition functions

- content/master/concepts/packages.md
- content/media/snippets/compose/claim-aws-new.yaml
- content/media/snippets/compose/claim-aws.yaml
- content/media/snippets/compose/claim-azure.yaml
- content/media/snippets/compose/claim-gcp.yaml
- content/media/snippets/compose/pod.yaml
- content/media/snippets/configure/aws/providerconfig.yaml
- content/media/snippets/configure/aws/setup.sh
- content/media/snippets/configure/azure/providerconfig.yaml
- content/media/snippets/configure/gcp/credentials.sh
- content/media/snippets/package/aws-with-vpc/composition.yaml
- content/media/snippets/package/aws-with-vpc/crossplane.yaml
- content/media/snippets/package/aws-with-vpc/definition.yaml
- content/media/snippets/package/aws/composition.yaml
- content/media/snippets/package/aws/crossplane.yaml
- content/media/snippets/package/aws/definition.yaml
- content/media/snippets/package/azure/composition.yaml
- content/media/snippets/package/azure/crossplane.yaml
- content/media/snippets/package/azure/definition.yaml
- content/media/snippets/package/definition.yaml
- content/media/snippets/package/gcp/composition.yaml
- content/media/snippets/package/gcp/crossplane.yaml
- content/media/snippets/package/gcp/definition.yaml
- content/media/snippets/provision/aws.yaml
- content/media/snippets/provision/azure.yaml
- content/media/snippets/provision/gcp.yaml
- content/v1.11/concepts/packages.md
- content/v1.12/concepts/packages.md
- content/v1.13/concepts/packages.md
The new weekly CI run for external links found references to files in the v1.10 folder that were deleted with the latest release. 
This restores the snippets folder until the packages page is rewritten and updates the links. 
> Fix broken links to snippets

- themes/geekboot/assets/scss/_accordion.scss
- themes/geekboot/assets/scss/_content.scss
- themes/geekboot/assets/scss/dark-mode.scss
- themes/geekboot/assets/scss/light-mode.scss
- Improve typography sizing and font-weight
- Improve spacing between titles
- Fix accordions to adhere to dark mode, and improve their styling with hover state
(accordion example can be found under "Hide long outputs" under /contribute/features/)
> improve typography, spacing, and accordions

- netlify_build.sh
The current build script generates a hugo config with a baseURL of the commit ID, not the PR number. 
Since deploy URLs are based on the PR number the baseURL doesn't match the PR and some files won't load properly because of browser and netlify security rules. 
This changes the base URL to be based on the PR number instead of the commit ID so everything aligns.
> Fix font loading in deploy previews

- content/master/concepts/packages.md
- content/v1.11/concepts/packages.md
- content/v1.12/concepts/packages.md
- content/v1.13/concepts/packages.md
The update in #512 used an incomplete path for the snippets location and it couldn't be tested until it was pushed.
This corrects the paths for the snippets.
> Fix snippets location in github

- content/knowledge-base/guides/import-existing-resources.md
- content/master/concepts/managed-resources.md
- content/v1.13/concepts/managed-resources.md
- themes/geekboot/assets/scss/dark-mode.scss
- utils/vale/styles/Crossplane/allowed-jargon.txt
- utils/vale/styles/Crossplane/crossplane-words.txt
Late update for the management policies alpha feature. 
Replaces the old `managementPolicy` to `managementPolicies`, updates the Importing guide and adds a section for `spec.initProvider`. 
Fixes: #497
> update management policies with GMP changes

- content/master/concepts/patch-and-transform.md
- content/v1.13/concepts/patch-and-transform.md
Fix links in table for patch types
> Fix links in table for patch types

- themes/geekboot/assets/scss/_content.scss
- themes/geekboot/assets/scss/_footer.scss
- themes/geekboot/assets/scss/_home.scss
- themes/geekboot/assets/scss/_search-button.scss
- themes/geekboot/assets/scss/_search-results.scss
- themes/geekboot/assets/scss/_variables.scss
- themes/geekboot/assets/scss/dark-mode.scss
- themes/geekboot/assets/scss/light-mode.scss
- Improve contrast for accordions/expandable blocks
- Improve coloring for "Join the Crossplane Slack" home page tooltip
- Replaced all old color variables with the new palette variables
- Fix dark mode coloring for vertical striped tables
- Remove table aqua background hover states
> Minor color improvements

- themes/geekboot/layouts/shortcodes/expand.html
As called out by @jbw976 in [another PR](https://github.com/crossplane/docs/pull/522#discussion_r1287425327) there is a problem with the bottom corners of expanded accordion/expand shortcode elements.
Looks like this may be issue [Bootstrap #38830](https://github.com/twbs/bootstrap/issues/38830).
This adds the workaround styling to the expand shortcode.
> fix expand box bottom corners on expand

- content/knowledge-base/guides/multi-tenant.md
- content/master/concepts/composition-functions.md
- content/master/concepts/providers.md
- content/master/software/install.md
- content/v1.11/concepts/providers.md
- content/v1.11/software/install.md
- content/v1.12/concepts/providers.md
- content/v1.12/software/install.md
- content/v1.13/concepts/composition-functions.md
- content/v1.13/concepts/providers.md
- content/v1.13/software/install.md
Multiple uses of `--set args=` in install docs use brackets instead of braces and fail to quote the braces. This corrects it across the docs.
> correct use of helm --set

- content/master/concepts/patch-and-transform.md
- content/v1.13/concepts/patch-and-transform.md
In the current Crossplane documentation, there is an incorrect example for the string formatting. This mistake might cause confusion for developers trying to write composition patches.
The incorrect example is given as:
patches:
- type: FromCompositeFieldPath
fromFieldPath: spec.field1
toFieldPath: metadata.annotations["stringAnnotation"]
transforms:
- type: string
string:
type: Format
format:
fmt: "the-field-%s"
However, the correct format syntax should eliminate the format key, as shown below:
patches:
- type: FromCompositeFieldPath
fromFieldPath: spec.field1
toFieldPath: metadata.annotations["stringAnnotation"]
transforms:
- type: string
string:
type: Format
fmt: "the-field-%s"
> Fix incorrect string format example in documentation

- content/master/getting-started/provider-aws.md
- content/v1.13/getting-started/provider-aws.md
As the monolithic provider-aws has been split into a provider family the authentication documentation has moved. This change updates the link to the updated location on docs.upbound.io.
> Update the link to the aws provider authentication docs

- content/master/getting-started/install-crossplane-include.md
- content/v1.13/getting-started/install-crossplane-include.md
- themes/geekboot/layouts/_default/sitemap.xml
Pages that are part of an `include` still exist as standalone Hugo pages, they are just hidden from the ToC. 
These pages are being included in the sitemap, which is used for indexing the docs for both local search and search engines. 
This adds a front matter setting, `searchExclude`, that when `true` will exclude the page from the sitemap. It also sets the front matter on the existing include pages.
> Remove included pages from local search and search engines

- content/master/concepts/compositions.md
- content/v1.13/concepts/compositions.md
Companion for https://github.com/crossplane/crossplane/pull/4399
I noticed MatchCondition was not yet documented. If this was intentional or if you'd rather it in a separate PR just let me know :-)
> Document MatchTrue, MatchFalse and MatchCondition readiness checks

- content/master/concepts/environment-configs.md
Documenting https://github.com/crossplane/crossplane/pull/4547 and https://github.com/crossplane/crossplane/pull/4568.
> feat: optional environment label selector fieldpath

- content/master/concepts/usages.md
- content/master/software/install.md
This PR adds documentation for alpha `Usage`s. 
The implementation PR is currently under review here: https://github.com/crossplane/crossplane/pull/4444
> Add documentation for alpha Usages

- content/master/concepts/managed-resources.md
- content/v1.13/concepts/managed-resources.md
Fixes #536 
There was not an example of the args section of the config for this feature. I've added one and moved the Important note to only highlight that the feature is in alpha.
Feel free to change or reject any changes.
> Adds managedPolicies config enablement

- content/master/concepts/compositions.md
- content/master/concepts/environment-configs.md
- content/master/concepts/patch-and-transform.md
- content/v1.13/concepts/compositions.md
- content/v1.13/concepts/environment-configs.md
- content/v1.13/concepts/patch-and-transform.md
Currently there are no docs on patching to an XR using an environment config using `spec.environment.patches` of a Composition. 
This adds details on this and removes an incorrect statement about the EC key needing to exist before writing to it.
> Update guidlines on envConfigs and patching to XRs

- content/master/concepts/composite-resources.md
- content/v1.13/concepts/composite-resources.md
Current snippet does not match actual behavior, and also what is documented in the KB: https://github.com/crossplane/docs/blob/daaa7ec019bf91dc75c474d45e67900a9a990e2d/content/knowledge-base/guides/composition-revisions-example.md#manual-update-policy
1. `compositionRevisionRef` is of type `Object`, not `String`.
2. `compositionUpdatePolicy` must be set to `Manual`, otherwise `compositionRevisionRef` is ignored (from my observations)
> Composite Resources: fix snippet on `compositionRevisionRef`

- content/master/concepts/managed-resources.md
- content/v1.11/concepts/managed-resources.md
- content/v1.12/concepts/managed-resources.md
- content/v1.13/concepts/managed-resources.md
The text "began creating a new managed resource." was in a table row by itself. Also, changed article from "a" to "the" for consistency with other rows, and removed the word "new" as it is redundant.
> Fixed formatting of annotation table in managed-resources.md.

- content/master/software/install.md
- content/v1.11/software/install.md
- content/v1.12/software/install.md
- content/v1.13/software/install.md
Hey, This must be a typo because there is no any reference to `manger`.
> Fix typo of Manager in install.md files

- content/knowledge-base/guides/troubleshoot.md
- content/master/concepts/packages.md
- content/v1.11/concepts/packages.md
- content/v1.11/getting-started/provider-aws-part-3.md
- content/v1.11/getting-started/provider-azure-part-3.md
- content/v1.11/getting-started/provider-gcp-part-3.md
- content/v1.12/concepts/packages.md
- content/v1.12/getting-started/provider-aws-part-3.md
- content/v1.12/getting-started/provider-azure-part-3.md
- content/v1.12/getting-started/provider-gcp-part-3.md
- content/v1.13/concepts/packages.md
Related to https://github.com/crossplane/crossplane/pull/4719 and https://github.com/crossplane/crossplane/issues/4697.
I hope I updated all places.
> docs: renaming kubectl plugin to crossplane CLI

- content/master/concepts/composition-functions.md
- content/v1.13/concepts/composition-functions.md
I corrected two typos in composition functions documentation. Because composition functions documentation doesn't exist in v1.11 and v1.12, there are no changes in those directories.
> Fix typos in composition functions documentation

- content/master/concepts/managed-resources.md
- content/v1.13/concepts/managed-resources.md
I added "Observe" management policy to "Create" and "Delete" policies, because it is required in all configurations except when pausing a resource.
v1.11 and v1.12 don't have this updated example, so they didn't change.
> Fix example configuration that uses an unsupported managementPolicy

- content/contribute/contribute.md
- themes/geekboot/layouts/partials/version-dropdown-menu.html
The dropdown menu with the version numbers builds links to the same page in another version if the Page title is the same. 
Because Hugo doesn't (directly) care about filenames and prefers focusing on file/page metadata it's much more difficult to match on file names than titles. 
This adds support for an optional frontMatter `altTitle` to allow authors to reference the older/original title. 
There are more flexible ways to do this but not without major build performance impact required to iterate over all pages multiple times.
> add support for matching pages when the page title changes

- content/master/software/install.md
This PR updates the table of Helm chart values to match the latest in https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/README.md.
This was spurred by https://github.com/crossplane/crossplane/pull/4831 where the default value for `image.repository` is changing, but I noticed a lot of other differences from `crossplane/crossplane` that hadn't made their way over to the docs, so I just copied the whole thing over in its entirety.
The history of recent changes to the helm chart readme in crossplane can be found at https://github.com/crossplane/crossplane/commits/master/cluster/charts/crossplane/README.md for curious reviewers.
Is there an process that could be in place to ensure the two stay in sync? 🤔 
Affected page in the deployment preview (don't forget to …
> Sync Helm chart values table from crossplane/crossplane repo

- content/master/concepts/compositions.md
- content/v1.13/concepts/compositions.md
The AWS platform ref was recently refactored moving the location of files referenced in the docs.
This updates the links to point to the new URLs
> fix links for moved platform ref files

- content/master/concepts/providers.md
- content/v1.12/concepts/providers.md
- content/v1.13/concepts/providers.md
Resolves #586.
Changes the wording about what happens when a provider is installed.
> Update providers to not say they install CRDs

- content/v1.14/concepts/composition-functions.md
Fixes https://github.com/crossplane/docs/issues/595
During development the CLI docs were in a different branch from the functions docs, so I linked to this PR as a placeholder. We can now link to the real docs.
> Link to CLI docs from functions docs

- content/master/cli/_index.md
- content/master/cli/command-reference.md
- content/master/concepts/composition-functions.md
new CLI docs weren't synced to master. This adds them.
Also adds the link missing in #599
> Create CLI docs in Master

- content/knowledge-base/guides/write-a-composition-function-in-go.md
- utils/htmltest/.htmltest.yml
- utils/vale/styles/Crossplane/allowed-jargon.txt
Fixes https://github.com/crossplane/docs/issues/579
This is separate from the functions documentation under concepts because:
1. I expect to have similar guides for other languages, such as Python.
2. The guide will evolve outside of the Crossplane release cycle.
> Add a guide to writing a composition function in Go

- content/master/concepts/packages.md
- content/v1.14/concepts/packages.md
Updates the old `crossplane build` commands to the correct syntax for the new 1.14 CLI.
> update cli commands to new syntax

- content/master/software/install.md
- content/v1.14/software/install.md
During the update of GMP to beta the `--enable-management-policies` flag was incorrectly added to the options for the Crossplane pod. 
This removes that reference. 
Fixes #605
> remove reference to management policies flag

- content/master/software/install.md
- content/v1.14/software/install.md
- netlify_build.sh
- themes/geekboot/layouts/partials/analytics.html
- themes/geekboot/layouts/partials/crds.html
- themes/geekboot/layouts/partials/rollworks.html
Rebased to master picking up #605 and #615.
Fixes issues with rendering CRDs where the top level isn't `spec` as well as list `items` inside a CRD.
Major improvements to expand/collapse buttons. 
Makes branch deploy previews render on Netlify.
> remove reference to management policies flag.  #605

- config.yaml
- content/v1.14/release-notes/docs.md
- themes/geekboot/assets/scss/_content.scss
- themes/geekboot/assets/scss/dark-mode.scss
- themes/geekboot/assets/scss/light-mode.scss
- themes/geekboot/layouts/_default/section.rss.xml
- themes/geekboot/layouts/partials/header.html
- themes/geekboot/layouts/partials/single-list.html
- utils/vale/styles/Crossplane/allowed-jargon.txt
Publishes an RSS feed for the release notes page and adds an icon and header meta tag for the RSS feed.
> add RSS support for release notes. Resolves #629

- themes/geekboot/layouts/partials/feature-state-alert.html
* Feature can be dropped only at alpha level
* Do not confuse beta features users with the statement that can block adoption
> Highlight possibility of feature drop only for alpha features

- themes/geekboot/layouts/partials/crds.html
The API page doesn't render in /latest. /latest is the entry point for search engines.
The reason is that the existing code looks for a version number that doesn't exist. This changes the logic to use the current directory instead of the version parameter. 
Verified by creating a /latest content dir and removing the version number.
> Fix issue with API folder on /latest

- content/v1.14/concepts/composition-functions.md
Changes the wording to only reference the existing Go function guide and links directly to it. 
Resolves #648
> Update link and wording for comp function guide

- content/master/concepts/packages.md
- content/v1.14/concepts/packages.md
Updated the build the package examples to use the correct flags for `xpkg build`.
- `--name` is now `--output`
- `-f` is now `--package-root`
I've updated the section in the `master` and `v1.14` docs.
> fix(concepts): correct xpkg build flags

- content/master/concepts/patch-and-transform.md
- content/v1.13/concepts/patch-and-transform.md
- content/v1.14/concepts/patch-and-transform.md
When you're missing the key, it does in fact fail and does not ignore the patch:
```
cannot apply the "CombineFromComposite" patch at index 0: transform at index 0 returned error: map transform could not resolve: key default/queue-sample is not found in map
```
Relevant [slack thread](https://crossplane.slack.com/archives/CEG3T90A1/p1701979187893449).
I took a look at the code and in all "live" versions we return an error from `ResolveMap` that gets propagated without special treatment that would allow it to be ignored, so I changed the note in all applicable versions (1.12 has no note I could find, but please let me know if would be nice if there was one).
> docs(transforms): note that map fails on missing keys

- content/knowledge-base/integrations/argo-cd-crossplane.md
Just reading the docs and found some types, directly fixed them :)
> Fix typos in argo-cd-crossplane.md

- themes/geekboot/assets/scss/_sidebar.scss
- themes/geekboot/assets/scss/dark-mode.scss
Recent restyling of the color theme missed some colors in the nav, on mobile, in dark mode.
This updates the colors of the expand/collapse buttons, close buttons and link colors on the dark mode mobile nav.
> fix sidebar colors in mobile darkmode

- content/master/getting-started/install-crossplane-include.md
- content/master/getting-started/provider-aws-part-2.md
- content/master/getting-started/provider-aws.md
- content/master/getting-started/provider-gcp-part-2.md
- content/master/getting-started/provider-gcp.md
- content/v1.14/getting-started/provider-aws-part-2.md
- content/v1.14/getting-started/provider-aws.md
- content/v1.14/getting-started/provider-gcp-part-2.md
- content/v1.14/getting-started/provider-gcp.md
- utils/vale/styles/Google/Headings.yml
Updates the AWS quickstart to v0.46.0 and GCP to v0.40.0.
> Update GCP and AWS Quickstarts to no-fork providers

- content/v1.14/software/install.md
In the list of feature flags for crossplane v1.14, `--enable-composition-functions` was still listed as `Alpha`. This pull request changes this to `Beta` as composition functions matured to beta with v1.14
> fix: composition function is beta

- content/master/concepts/pods.md
- content/master/getting-started/install-crossplane-include.md
- content/master/software/install.md
It's going away per https://github.com/crossplane/crossplane/issues/5227. See also https://github.com/crossplane/crossplane/issues/5227.
> Remove mention of the RBAC manager management policy

- .gitignore
- content/master/concepts/composite-resource-definitions.md
- content/v1.13/concepts/composite-resource-definitions.md
- content/v1.14/concepts/composite-resource-definitions.md
Updated the description of the `defaultCompositeDeletePolicy` property as a result of https://github.com/crossplane/crossplane/issues/5301
Also updated .gitignore to include the .idea directory created by PyCharm
> Improve documentation of defaultCompositeDeletePolicy

- content/knowledge-base/integrations/argo-cd-crossplane.md
Fixes mistake by #673. In Lua, the inequality operator is `~=` not `!=`. This caused an ArgoCD ComparisonError and sync failure.
```
error setting app health: failed to get resource health for "ProviderConfig" with name "azure" in namespace "": <string> line:27(column:56) near '!': Invalid token
```
> fix: Invalid inequality operator in ArgoCD custom health for ProviderConfig

- content/master/cli/command-reference.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
Adds info about `crossplane beta xpkg init` hooks that were added in https://github.com/crossplane/crossplane/pull/5190
Also adds the python composition template to the known templates
Fixes: #670
> add Crossplane CLI init hooks reference

- content/master/concepts/managed-resources.md
These annotations were introduced in https://github.com/crossplane/crossplane-runtime/pull/283.
Per https://github.com/crossplane/crossplane/issues/3037 folks find these annotations hard to reason about. That's understandable, because they're doing a lot of subtle things.
This section ended up super long, but I think this is an area where folks really need to understand what's happening in order to make good decisions when Crossplane refuses to proceed.
> Document the crossplane.io/external-create-... annotations

- content/master/concepts/patch-and-transform.md
- content/v1.13/concepts/patch-and-transform.md
- content/v1.14/concepts/patch-and-transform.md
As confirmed @phisco in [Slack](https://crossplane.slack.com/archives/CEG3T90A1/p1706970216073849?thread_ts=1706970216.073849&cid=CEG3T90A1), the 'patch and transform' documentation is wrong about the impossibility to use data from `.status.atProvider` in the `fromFielPath` of the `ToEnvironmentFieldPath` patch.
This restriction is incompatible with the example in the `EnvironmentConfig` page that shows it is :
```
patches:
- type: ToEnvironmentFieldPath
fromFieldPath: status.atProvider.id
toFieldPath: vpcId
```
https://docs.crossplane.io/latest/concepts/environment-configs/#patch-an-individual-resource
> Remove false restriction about using '.status.atProvider' into ToEnvironmentFieldPath

- content/master/concepts/composition-functions.md
- content/v1.14/concepts/composition-functions.md
The annotations are expected to be under the "annotations" key. Currently, the docs instruct user to use "annotation".
Copy pasting the example won't work. This can be quite confusing as the user will continue to see function containers spin-up and the local function instance ignored.
> Fix composite functions "annotations" key

- themes/geekboot/assets/scss/_content.scss
- themes/geekboot/assets/scss/dark-mode.scss
- themes/geekboot/assets/scss/light-mode.scss
- themes/geekboot/layouts/shortcodes/table.html
Fixes the coloring for tables in dark mode. 
Examples of rendered tables:
* https://deploy-preview-700--crossplane.netlify.app/contribute/features/#tables
* https://deploy-preview-700--crossplane.netlify.app/v1.14/software/install/#customize-the-crossplane-helm-chart (expand the "All Crossplane customization options" folded section)
* https://deploy-preview-700--crossplane.netlify.app/v1.14/concepts/patch-and-transform/#types-of-patches
This addresses tables for light and dark mode as well as striped, hover and standard tables. 
Resolves #690.
> Fix table colors in dark mode

- content/master/cli/command-reference.md
Adds the [newly added](https://github.com/crossplane/crossplane/pull/5389) known template to the docs.
> add cfg-template to known init templates

- content/master/cli/command-reference.md
Adds the `init --ref-name` [flag](https://github.com/crossplane/crossplane/pull/5391) to docs.
> add `init` --ref-name flag

- content/knowledge-base/guides/composition-revisions-example.md
- content/knowledge-base/guides/composition-revisions.md
- content/master/software/install.md
Relates to https://github.com/crossplane/docs/issues/709. I don't think it's a complete 'fix'.
Revisions became GA in v1.12 per https://github.com/crossplane/crossplane/issues/3715. I think there's more to do to integrate them into the main docs flow as a GA feature, but at minimum let's stop actively saying they're beta.
When the feature became GA, we:
* Made it impossible to disable the feature using the flag.
* Hid the feature flag from the help output.
* Log a warning that the flag will be removed if it is passed.
> Don't say composition revisions are beta

- content/master/concepts/_index.md
- content/v1.13/concepts/_index.md
- content/v1.14/concepts/_index.md
- content/v1.15/concepts/_index.md
This rewrites the /concepts root page to add new top-level components (Composition functions, Usages) and to pass vale. 
This update also slims down the descriptions of each component to not create too much duplication for what's detailed inside each individual component.
Resolves #617  ([Boston represent](https://en.wikipedia.org/wiki/Area_codes_617_and_857))
> Rewrite Concepts root page

- OWNERS.md
We (I) forgot to update the owners file since Bob was moved to Crossplane Maintainer status.
> promote Bob to Maintainer and move Dan to Emeritus

- content/v1.13/concepts/patch-and-transform.md
- content/v1.14/concepts/patch-and-transform.md
In #549 we removed references that envkeys had to exist before a patch, but missed some references. This should clean up the remaining references.
> remove incorrect restriction about envkeys in patches

- themes/geekboot/assets/scss/_mermaid.scss
- themes/geekboot/assets/scss/docs.scss
Mermaid diagrams were introduced in around the 1.14 docs release and have had display issues since day-1.
This fixes the (current) problems with mermaid diagrams displaying in both light and dark mode. Using the two examples we have today
Light:
Dark:
Additional styles can be added if there are display problems in the future
Resolves #592
> Fix mermaid diagrams in light/dark mode

- content/master/concepts/server-side-apply.md
- content/master/software/install.md
- content/v1.15/concepts/server-side-apply.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
- utils/vale/styles/Crossplane/crossplane-words.txt
Fixes https://github.com/crossplane/docs/issues/698
This feature flag changes how the claim controller works. It's a bug fix. We usually wouldn't put a bug fix behind a feature flag, but this one introduces several behavior changes that we don't want to catch people unaware.
> Document the --enable-claim-ssa feature flag

- content/master/concepts/packages.md
- content/v1.14/concepts/packages.md
- content/v1.15/concepts/packages.md
The flag in `xpkg build` was changed from `--output` to `--package-file` and was missed in the Packages concept doc. 
These are the only three places that `--output` was missed.
Resolves #689
> corrects xpkg build output flag. 

- content/master/concepts/managed-resources.md
- content/v1.14/concepts/managed-resources.md
- content/v1.15/concepts/managed-resources.md
Adds a note that managed resources with a pause annotation can't be deleted.
Resolves #573
> Add a callout that paused resources can't be deleted

- content/master/concepts/managed-resources.md
- content/v1.13/concepts/managed-resources.md
- content/v1.14/concepts/managed-resources.md
- content/v1.15/concepts/managed-resources.md
- themes/geekboot/layouts/shortcodes/check.html
Creates a shortcode that inserts a ✔️ with a CSS style to set the color of the emoji to the same as the body font color. This makes ✔️ black in light mode and white in dark mode.
The only place we use the ✔️ is in the table for MR management policies:
https://deploy-preview-714--crossplane.netlify.app/v1.15/concepts/managed-resources/#managementpolicies
Resolves #523 
> shortcode to have checkmark emoji use the body font color

- content/master/getting-started/provider-aws-part-2.md
- content/master/getting-started/provider-aws.md
- content/master/getting-started/provider-azure.md
- content/master/getting-started/provider-gcp.md
- content/v1.14/getting-started/provider-azure.md
- content/v1.14/getting-started/provider-gcp.md
- content/v1.15/getting-started/provider-aws-part-2.md
- content/v1.15/getting-started/provider-aws.md
- content/v1.15/getting-started/provider-azure.md
- content/v1.15/getting-started/provider-gcp.md
Adds links to the docs.upbound.io authentication docs for each provider.
For v1.15 and master this also upgrades provider AWS to v1..1.0
Resolves #533
> add links to provider auth docs and upgrade AWS to 1.1.0

- content/master/cli/command-reference.md
- content/v1.15/cli/command-reference.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
Changes some organization and provides more structure to the examples for `crossplane beta validate`.
> Post-release cleanup and expanded examples for beta validate

- content/master/software/upgrade.md
- content/v1.15/software/upgrade.md
Adds instructions on how to Upgrade Crossplane with Helm along with guidelines for updating new default settings. 
Resolves #545
> add upgrade guides

- content/master/release-notes/docs.md
- content/v1.15/release-notes/docs.md
Adds doc release notes for the new content and docs features/fixes since the 1.15 release.
> add RNs for recent docs changes

- content/master/getting-started/provider-aws-part-2.md
- content/v1.15/getting-started/provider-aws-part-2.md
This PR adds the missing `v` prefix to the tags of the S3 and DynamoDB packages used in the 'AWS Quickstart Part 2' documentation.
Fixes #724.
> Fix Incorrect Package Tags In 'AWS Quickstart Part 2'

- content/master/getting-started/provider-azure-part-2.md
- content/master/getting-started/provider-azure.md
- content/v1.15/getting-started/provider-azure-part-2.md
- content/v1.15/getting-started/provider-azure.md
I was following the Azure quickstart docs but had trouble getting it to work.
The error I got was the following:
```
Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer: could not parse Azure CLI version: launching Azure CLI: exec: "az": executable file not found in $PATH
```
Which seemed like an issue with Terraform after some superficial searching but not too sure what was going on.
I was using [client certificates for authorization](https://docs.upbound.io/providers/provider-azure/authentication/#create-a-service-principal-with-client-certificate-credentials-using-the-azure-cli-tool) and after looking at the provider versioning realized that this was only introduced in [v0.40.0](https://docs.upbound.io/providers/provider-azure/#v0400) and …
> Fix: update quickstart azure provider version

- content/master/concepts/usages.md
- content/v1.14/concepts/usages.md
- content/v1.15/concepts/usages.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
Documenting the configuration introduced by https://github.com/crossplane/crossplane/pull/5394
> Document Usage replayDeletion

- content/master/release-notes/docs.md
- content/v1.15/release-notes/docs.md
- themes/geekboot/layouts/partials/single-list.html
- utils/htmltest/.htmltest.yml
Fixes broken external links and changes the link checking tool's default of stripping query strings to it properly validates youtube links.
> External link fixes

- content/master/concepts/_index.md
- content/v1.13/concepts/_index.md
- content/v1.14/concepts/_index.md
- content/v1.15/concepts/_index.md
Fixes wrong link for compositions from `composite-resources` to `compositions`
> Fixes wrong link for compositions 

- content/knowledge-base/integrations/argo-cd-crossplane.md
This fixes the health status for `ProviderConfig` objects, that kept being reported as _Progressing_ in ArgoCD.
The reason is that the script was only checking for `nil` values in the status and conditions fields. In Lua, an empty table is not the same as `nil`. In the `ProviderConfig` object, the `status` field is an empty object `status: {}`.
```yaml
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
annotations:
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
argocd.argoproj.io/tracking-id: [REDACTED]:azure.upbound.io/ProviderConfig:crossplane-system/azure-workload-identity
creationTimestamp: "2024-04-09T13:33:11Z"
finalizers:
- in-use.crossplane.io
generation: 1
name: azure-workload-identity
resourceVersion: "19576"
uid: …
```
> fix: Objects with .status: {} should return Healthy

- content/master/concepts/patch-and-transform.md
- content/v1.13/concepts/patch-and-transform.md
- content/v1.14/concepts/patch-and-transform.md
- content/v1.15/concepts/patch-and-transform.md
> Corrects usage of Trim Prefix/Suffix. 

- .github/PULL_REQUEST_TEMPLATE.md
Adds a PR template with links to the Docs contrib guide with info on using vale, running Hugo locally and using Hugo features.
> Add PR Template linking to docs contrib guide

- config.yaml
- content/contribute/code-style-guide.md
- content/contribute/contribute.md
- content/contribute/infrastructure.md
- content/contribute/vale.md
- netlify.toml
- netlify_build.sh
- postcss.config.js
- utils/vale/styles/Crossplane/brands.txt
- utils/webpack/src/js/colorMode.js
- utils/webpack/src/js/customClipboard.js
- utils/webpack/src/js/globalScripts.js
- utils/webpack/src/js/hoverHighlight.js
- utils/webpack/src/js/slackNotify.js
Adds additional comments in scripts and files and expands the infra documentation to cover Netlify, search, building and more.
> Add a bunch more contrib info

- .github/ISSUE_TEMPLATE/new_release.md
Updates the hugo config line number, API yaml folder destination and adds details on what version number needs to change in the new release issue template.
> Update changed info in release issue template

- config.yaml
Fixes https://github.com/crossplane/docs/issues/765
> Update version dropdown

- content/master/guides/write-a-composition-function-in-go.md
- content/master/guides/write-a-composition-function-in-python.md
- content/v1.14/guides/write-a-composition-function-in-go.md
- content/v1.14/guides/write-a-composition-function-in-python.md
- content/v1.15/guides/write-a-composition-function-in-go.md
- content/v1.15/guides/write-a-composition-function-in-python.md
- content/v1.16/guides/write-a-composition-function-in-go.md
- content/v1.16/guides/write-a-composition-function-in-python.md
The URLs are not enclosed by bracket "()".
-->
> fix: broken links

- content/master/cli/command-reference.md
- content/v1.16/cli/command-reference.md
> Update crossplane CLI version flag

- content/master/software/install.md
Relates to https://github.com/crossplane/crossplane/pull/5795
> Add Information For Configuring Topology Spread Constraints in Helm Chart

- content/master/cli/command-reference.md
- content/v1.16/cli/command-reference.md
Adds the improvements made at PR https://github.com/crossplane/crossplane/pull/5791 to `beta validate` command's reference docs for informational purposes.
> add unknown field check to validate command

- content/v1.14/concepts/composition-functions.md
- content/v1.15/concepts/composition-functions.md
- content/v1.16/concepts/composition-functions.md
Minor fixing indent in all versions of `composition-functions.md`
> Fix indent in composition-functions.md

- content/master/concepts/composition-revisions.md
- content/v1.15/concepts/composition-revisions.md
- content/v1.16/concepts/composition-revisions.md
- content/v1.17/concepts/composition-revisions.md
Description and context provided in https://github.com/crossplane/docs/pull/792#pullrequestreview-2266770668
> Fix compositionrevision docs

- content/master/guides/write-a-composition-function-in-go.md
- content/v1.17/guides/write-a-composition-function-in-go.md
Adds examples of communicating to the user by setting status conditions and emitting events.
Related to https://github.com/crossplane/docs/issues/795.
> Claim Communication Examples

- content/master/getting-started/provider-azure-part-2.md
- content/v1.17/getting-started/provider-azure-part-2.md
This is an unnecessary patch that breaks the composition.
> Remove quickstart-subnet location patch

- content/master/guides/write-a-composition-function-in-go.md
- content/v1.17/guides/write-a-composition-function-in-go.md
This docs PR updates the go function guide to use the latest experience (minor updates) from `function-sdk-go:v0.3.0`.
This is a companion PR to https://github.com/crossplane/function-template-go/pull/81 which updates the function-template-go repo to use the latest SDK release also.
I've tested this by walking through the entire guide locally using these updated steps and everything is working OK ✅
> bump go function guide to latest function-sdk-go:v0.3.0 experience

- content/master/concepts/packages.md
> A few grammatical updates

- content/master/concepts/providers.md
- content/master/getting-started/introduction.md
- content/v1.17/concepts/providers.md
- content/v1.17/getting-started/introduction.md
Following the addition of the new [public package registries page](https://www.crossplane.io/registries) on crossplane.io with https://github.com/crossplane/website/pull/63, this PR updates a couple of links in the docs to now point to this new registry index/listing page instead.
> Link to crossplane website's new public package registries page

- content/master/cli/command-reference.md
- content/v1.17/cli/command-reference.md
- utils/vale/styles/Crossplane/crossplane-words.txt
Add the `extra-resources` option to the CLI command for 1.17 and master. 
Fixes #817 
```shell
$ vale --config="utils/vale/.vale.ini" content/master/cli/command-reference.md     
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
$ vale --config="utils/vale/.vale.ini" content/v1.17/cli/command-reference.md
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
```
> add extra-resources to cli docs

- content/master/concepts/environment-configs.md
- utils/vale/styles/Crossplane/crossplane-words.txt
This PR updates the docs to include information about how to use `EnvironmentConfigs` with `function-environment-configs`. This will help Crossplane users migrate their `Compositions` due to the impact of maturing `EnvironmentConfig` to Beta while removing native composition support for them in https://github.com/crossplane/crossplane/pull/5938.
> update composition environment docs to function-environment-configs

- content/master/api/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
- content/master/api/crds/apiextensions.crossplane.io_compositionrevisions.yaml
- content/master/api/crds/apiextensions.crossplane.io_compositions.yaml
- content/master/api/crds/apiextensions.crossplane.io_environmentconfigs.yaml
- content/master/api/crds/apiextensions.crossplane.io_usages.yaml
- content/master/api/crds/pkg.crossplane.io_configurationrevisions.yaml
- content/master/api/crds/pkg.crossplane.io_configurations.yaml
- content/master/api/crds/pkg.crossplane.io_controllerconfigs.yaml
- content/master/api/crds/pkg.crossplane.io_deploymentruntimeconfigs.yaml
- content/master/api/crds/pkg.crossplane.io_functionrevisions.yaml
- content/master/api/crds/pkg.crossplane.io_functions.yaml
- content/master/api/crds/pkg.crossplane.io_imageconfigs.yaml
- content/master/api/crds/pkg.crossplane.io_locks.yaml
- content/master/api/crds/pkg.crossplane.io_providerrevisions.yaml
- content/master/api/crds/pkg.crossplane.io_providers.yaml
- content/master/api/crds/secrets.crossplane.io_storeconfigs.yaml
- content/master/concepts/_index.md
- content/master/concepts/image-configs.md
- content/v1.16/concepts/_index.md
- content/v1.16/concepts/image-configs.md
- content/v1.17/concepts/_index.md
- content/v1.17/concepts/image-configs.md
- content/v1.18/concepts/_index.md
- content/v1.18/concepts/image-configs.md
- utils/vale/styles/Crossplane/crossplane-words.txt
Adds documentation for ImageConfig:
- Authentication goes to all master, v1.16, v1.17 and v1.18 version.
- Signature verification goes to master and v1.18 only.
It also updates `content/master/api/crds` with latest CRDs.
> Add documentation for ImageConfig

- content/master/concepts/packages.md
- content/master/concepts/providers.md
- content/master/software/install.md
- content/v1.18/concepts/packages.md
- content/v1.18/concepts/providers.md
- content/v1.18/software/install.md
> pkg-mgr: Add digest support and `enable-dependency-version-upgrades` flag

- content/master/concepts/environment-configs.md
- content/master/getting-started/install-crossplane-include.md
- content/master/guides/function-patch-and-transform.md
- content/v1.18/concepts/environment-configs.md
- content/v1.18/getting-started/install-crossplane-include.md
- content/v1.18/guides/function-patch-and-transform.md
* EnvironmentConfig was [promoted](https://github.com/crossplane/crossplane/pull/5938) to v1beta1 in 1.18
* Fix v1alpha1 -> v1beta1 for EnvironmentConfig in documentation
* Remove EnvironmentConfig related alpha warnings
* Occasional end of string whitespace busting
> EnvironmentConfig v1beta1 promotion related changes

- content/master/concepts/providers.md
- content/master/guides/troubleshoot-crossplane.md
- content/v1.17/concepts/providers.md
- content/v1.17/guides/troubleshoot-crossplane.md
Remove references to `ControllerConfig` in the troubleshooting guide, replace with `DeploymentRuntimeConfig` examples. 
Fixes #821 
The vale warnings are all on the existing docs, not the changed content.
> Remove ControllerConfig references in the troubleshooting guide

- content/master/concepts/usages.md
This PR updates the documentation for promoting Usage API to beta.
> Promote Usage API to beta

- content/master/cli/command-reference.md
- content/master/concepts/providers.md
- content/master/getting-started/provider-aws-part-2.md
- content/master/getting-started/provider-aws.md
- content/master/getting-started/provider-azure-part-2.md
- content/master/getting-started/provider-azure.md
- content/master/getting-started/provider-gcp-part-2.md
- content/master/getting-started/provider-gcp.md
- content/master/software/uninstall.md
Provider versions change constantly, and updating the examples in the docs with every release is not feasible.
Users of the docs sometimes end up installing very old versions of the providers, which results in a sub-optimal experience and the need for help.
This PR introduces two main changes:
1. The provider version to be installed is set to the major version only, e.g., v1 instead of v1.2.3. This has the effect of installing the latest provider version of the v1 major release. Note this capability is limited to the Upbound Marketplace for the providers used in the Quickstart guide.
2. Updates the example output where provider versions are listed all to v1.0.0 for consistency.
> Simplify provider versions in examples

- content/v1.18/guides/troubleshoot-crossplane.md
This PR simply ports the removal of `ControllerConfig` refs in troubleshooting guide to v1.18. This was missed in https://github.com/crossplane/docs/pull/822, which may have accidentally ported it to v1.17 instead of v1.18. The date on that PR was after the v1.18 release, so I think it was just an accident.
I noticed this today when trying to reference how to enable DEBUG logs for providers in https://docs.crossplane.io/v1.18/guides/troubleshoot-crossplane/#provider-logs today for someone and being surprised there was still a `ControllerConfig` reference in there.
> docs: port removal of ControllerConfig refs in troubleshooting guide to v1.18

- content/master/software/install.md
- content/v1.17/software/install.md
- content/v1.18/software/install.md
I noticed that Feature Flags documentation heavily deviates from reality.
I built and looked into the output of `./crossplane core start --help` from https://github.com/crossplane/crossplane/ `main,` `v1.18.2`, and `v1.17.4` tags.
e.g.
```
git checkout v1.18.2
cd cmd/crossplane
go build -o crossplane
./crossplane core start --help
...
Alpha Features:
--enable-external-secret-stores         Enable support for External Secret Stores.
--enable-usages                         Enable support for deletion ordering and resource protection with Usages.
--enable-realtime-compositions          Enable support for realtime compositions, i.e. watching composed resources and reconciling compositions
immediately when any of the composed resources is updated.
--enable-ssa-claims                     Enable …
```
> Fix documented Feature Flags for main, 1.18 and 1.17

- content/master/software/install.md
This PR simply bumps the feature flag for claim server side apply (`--enable-ssa-claims`) to Beta. This is the docs update companion PR to https://github.com/crossplane/crossplane/pull/6241.
Looks like my editor also auto removed a lot of trailing whitespace, sorry for the extra clean up 😇
> update feature flags for claim SSA promotion to beta

- content/master/concepts/packages.md
These are introduced in https://github.com/crossplane/crossplane/pull/6200.
They replace the old format, which is marked deprecated.
> Use new apiVersion and kind style dependencies in example

- content/v1.18/guides/crossplane-with-argo-cd.md
This adds the new ImageConfig resource to the ArgoCD LUA script so that it can be synced properly.
Without this, the sync just spins forever blocking further updates on the ArgoCD App.
> Add ImageConfig to Argo lua script

- content/master/concepts/packages.md
- content/master/concepts/pods.md
- content/master/concepts/providers.md
- content/v1.17/concepts/pods.md
- content/v1.18/concepts/pods.md
- content/v1.19/concepts/packages.md
- content/v1.19/concepts/pods.md
- content/v1.19/concepts/providers.md
This PR documents how people can enable automatic dependency version upgrade and downgrade functionalities.
> Document automatic dependency downgrade option

- content/master/software/upgrade.md
- content/v1.17/software/upgrade.md
- content/v1.18/software/upgrade.md
- content/v1.19/software/upgrade.md
Fix typo on Helm Upgrade command with arguments
Fixes [#6267](https://github.com/crossplane/docs/issues/885)
I have:
* []  Added or updated unit tests.
* []  Added or updated e2e tests.
> Fix typo on Helm Upgrade command with arguments

- content/master/concepts/compositions.md
- content/master/getting-started/provider-aws-part-2.md
- content/master/getting-started/provider-azure-part-2.md
- content/master/getting-started/provider-gcp-part-2.md
- content/master/guides/function-patch-and-transform.md
Updates the master folder of the docs to use the latest version of the transform and patch function so that a user following the quickstart will be successful.
There are some whitespace changes that made their way into this PR too. I'm not sure why. I tried to exclude them, but the files are changed when I run `git add`. I checked for Git hooks and the like, but didn't see any. Let me know if this is an issue.
**Background:**
I found when completing the GCP quickstart that during part 2, it fails when you get to the step where you apply a `Function`. The function never reaches the installed state because it cannot fetch the package:
```
cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request …
```
> Update function-patch-and-transform version to 0.8.2

- content/v2.0-preview/get-started/get-started-with-managed-resources.md
Don't repeat it.
This is a follow on from https://github.com/crossplane/docs/pull/896. That PR actually deleted the install include, but the document is actually including the file from the `content/master` directory, not the new `content/2.0-preview` directory. 🙃
> [v2] Link to Crossplane install guide

- themes/geekboot/assets/scss/docs.scss
We notice Mermaid styling looks good in Hugo (locally) but not when pushed to Netlify. Maybe this is why?
https://docs.crossplane.io/contribute/infrastructure/#how-optimization-works
> Ignore Mermaid styling when purging CSS

- content/v2.0-preview/get-started/get-started-with-managed-resources.md
This PR updates the "Get started with Managed Resources" guide to work with the v2 preview compatible AWS provider.
* the provider version was updated to the latest build for v2
* namespaced managed resources are used
* a new section introduces the big change of namespaced managed resources and what they look like
> full walkthrough for get started with managed resources guide

- content/contribute/infrastructure.md
- content/v2.0-preview/get-started/install.md
- themes/geekboot/layouts/partials/old-version-alert.html
- themes/geekboot/layouts/partials/preview-version-alert.html
- themes/geekboot/layouts/partials/single-list.html
This'll match any version ending with "-preview" and show a warning that it's a preview, instead of warning that it's an old version.
> Use a different warning for preview versions

- content/v2.0-preview/cli/_index.md
This PR just updates the CLI installation instructions in the v2.0-preview docs to always use `XP_CHANNEL=preview`. This way, when using v2, folks will download and install the Crossplane CLI from the v2 preview.
The command in action:
```
❯ curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/main/install.sh" | XP_CHANNEL=preview sh
crossplane CLI downloaded successfully! Run the following commands to finish installing it:
sudo mv crossplane /usr/local/bin
crossplane --help
Visit https://crossplane.io to get started. 🚀
Have a nice day! 👋
❯ sudo mv crossplane /usr/local/bin
```
This gives me the latest version from the v2 preview:
```
❯ crossplane version
Client Version: v2.0.0-preview.0.39.g815fa2bba
...
```
> v2: use XP_CHANNEL=preview for CLI install

- content/master/cli/command-reference.md
See https://github.com/crossplane/crossplane/issues/6003
> Update validate flags for new error on missing schemas flag

- content/v2.0-preview/composition/compositions.md
- content/v2.0-preview/get-started/get-started-with-composition.md
- content/v2.0-preview/whats-new/_index.md
Add refs from other pages where it might come up.
I also added a bit of detail and rephrased to address some Vale linter warnings.
This is a follow-up from https://github.com/crossplane/docs/pull/911.
> [v2] Move manual RBAC documentation to compositions page

- content/master/concepts/providers.md
- content/master/getting-started/introduction.md
- content/v1.17/concepts/providers.md
- content/v1.17/getting-started/introduction.md
- content/v1.18/concepts/providers.md
- content/v1.18/getting-started/introduction.md
- content/v1.19/concepts/providers.md
- content/v1.19/getting-started/introduction.md
- content/v2.0-preview/packages/providers.md
> Update dead link in providers.md

- content/master/software/install.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
Related PR : https://github.com/crossplane/crossplane/pull/6387
Related issue : https://github.com/crossplane/crossplane/issues/6386
> Add `runtimeClassName` value to crossplane helm chart docs

- OWNERS.md
This PR makes the following changes to the OWNERS.md file:
* add tr0njavolta as new maintainer
* add phisco as maintainer since he's a core maintainer
* add jbw976 to diff list from crossplane repo
* move muvaf to emeritus
* organize maintainer list so it's in same order as crossplane repo
Most all of these changes are just housekeeping organization, the main change here is adding @tr0njavolta as a new maintainer. They have been focusing on documentation in multiple dimensions and will be a valuable resource for keeping this project healthy and sustainable. 🙏
> chore: update OWNERS.md

- content/master/guides/change-logs.md
This PR adds a guide for enabling and using the change logs feature. It walks through a simple scenario with `provider-kubernetes` to enable change logs on the provider, create some resources and perform lifecycle operations on them, and how to check the change logs to learn more about the operations that were recorded.
I encourage reviewers to walk through the guide on the preview site and verify it works for them too. I have done so multiple times on my machine, but it would be good to get further validation.
Fixed #806
> change logs guide

- content/master/api/crds/apiextensions.crossplane.io_usages.yaml
- content/master/api/crds/pkg.crossplane.io_configurationrevisions.yaml
- content/master/api/crds/pkg.crossplane.io_configurations.yaml
- content/master/api/crds/pkg.crossplane.io_functionrevisions.yaml
- content/master/api/crds/pkg.crossplane.io_functions.yaml
- content/master/api/crds/pkg.crossplane.io_imageconfigs.yaml
- content/master/api/crds/pkg.crossplane.io_locks.yaml
- content/master/api/crds/pkg.crossplane.io_providerrevisions.yaml
- content/master/api/crds/pkg.crossplane.io_providers.yaml
- content/master/concepts/packages.md
- content/master/concepts/providers.md
- content/master/software/install.md
While authoring the release notes for the [v1.20 RC](https://github.com/crossplane/crossplane/releases/tag/v1.20.0-rc.1) today, I was reminded of a handful of changes to our feature flags, helm chart values, and APIs that should also be updated in the docs.  I am only updating master now and that will become the new v1.20 version on release day.
I've split it into 3 commits to make browsing a bit easier:
* updating feature flags and helm chart values
* updating the explanation and usage of the `--enable-dependency-version-downgrades` flag
* updating the core Crossplane CRDs (simply by copying them over from crossplane [`main` branch](https://github.com/crossplane/crossplane/tree/main/cluster/crds)
The CRD updates look to pick up a few changes that were actually part of the v1.19 release - …
> Update feature flags, helm chart values, and APIs for v1.20

- content/master/concepts/image-configs.md
- content/v1.20/concepts/image-configs.md
While we're here, move the common content on matching and debugging to their own top-level headings, since they apply to all the different ImageConfig features.
> Document the ImageConfig path rewriting feature in Crossplane 1.20

- content/master/concepts/compositions.md
This PR complements/depends on this crossplane PR https://github.com/crossplane/crossplane/pull/6372
It adds documentation for the new crossplane render annotation `render.crossplane.io/runtime-docker-env`
> add documentation to cover the new render annotation

- content/master/concepts/connection-details.md
- content/v1.18/concepts/connection-details.md
- content/v1.19/concepts/connection-details.md
- content/v1.20/concepts/connection-details.md
I think the change is quite obvious. A less destructive way of updating the keys should be documented.
I believe that this is probably not needed anymore in crossplane v2 but for the time being let's safe users from some headaches.
> Add alternative options to update connectionSecretKeys

- content/v2.0-preview/get-started/get-started-with-managed-resources.md
This PR just bumps the v2 getting started with MRs guide to use the latest provider-upjet-aws preview version of `v1.24.0-crossplane-v2-preview.0`.
> v2: bump provider-upjet-aws to latest preview version

- content/master/composition/compositions.md
- content/master/get-started/install.md
- content/master/guides/function-patch-and-transform.md
- content/master/guides/pods.md
- content/master/operations/operation.md
* Fixes https://github.com/crossplane/docs/issues/954
* Fixes https://github.com/crossplane/docs/issues/932
* Fixes https://github.com/crossplane/docs/issues/931
* Fixes https://github.com/crossplane/docs/issues/926
> A few low-hanging fruit docs fixes

- content/master/composition/compositions.md
- content/v2.0/composition/compositions.md
Right now AFAIK only function-python supports this.
> Document using required (fka extra) resources in compositions

- content/master/guides/upgrade-to-crossplane-v2.md
- content/master/whats-new/_index.md
- content/v2.0/guides/upgrade-to-crossplane-v2.md
- content/v2.0/whats-new/_index.md
The key points I want to get across with this guide is:
1. Who can upgrade (what breaking changes we made)
2. That there's no tooling to automate migration yet
3. That you can upgrade and start using v2 features anyway
> Guide for updating v1 -> v2

- content/v2.0/packages/image-configs.md
The rewrite feature of `ImageConfig` was merged around the time v2 work started, and as a result the docs for it were lost in v2. Re-introduce the missing docs from 1.20.
> Restore v1.20 ImageConfig docs that were lost in v2.0

- content/master/guides/crossplane-with-argo-cd.md
- content/v2.0/guides/crossplane-with-argo-cd.md
In Crossplane v2, some of the resources that didn't used to have statuses now do, so we check those conditions.  We also add a new resource, `ClusterProviderConfig`, which doesn't have a status.
> Update argo-cd health check ConfigMap for v2 resources

- content/master/packages/providers.md
- content/v2.0/packages/providers.md
This moves HTML comments out of paragraphs because they're creating breaks. I couldn't find a way to inline these comments without adding a paragraph break, let me know if there's a way to fix the doc while keeping linter exceptions fine grained.
> Fix unintended paragraph breaks

- content/master/packages/configurations.md
- content/master/packages/functions.md
- content/master/packages/providers.md
- content/v2.0/packages/configurations.md
- content/v2.0/packages/functions.md
- content/v2.0/packages/providers.md
Starting in v2.0, there is no longer a concept of a default registry.
Looks like my editor also removed trailing whitespace on some lines, but the key changes are simply removing the dialog starting with this content from all package content pages in version 2.0 and master, example https://docs.crossplane.io/v2.0/packages/providers/#install-a-provider: 
> "Beginning with Crossplane version 1.20.0 Crossplane uses the [crossplane-contrib](https://github.com/orgs/crossplane-contrib/packages) GitHub Container Registry at xpkg.crossplane.io by default for downloading and installing packages."...
I left them in older versions because they are still applicable there.
> Remove stale note about default registry
