- _includes/values.inc
- _layouts/docs.html
- docs/latest.html
e.g. /docs/master would redirects to /docs/master/ so just starting with /docs/master/
> Add a /doc/latest and fix issues with redirecting.

- _layouts/docs.html
- _scss/vars.scss
- css/docs.scss
- css/main.scss
- docs/latest.html
width as well as docs header in mobile view. Various other fixes.
> Fix the layout of the docs header and page to match site wide max

- 404.html
- _layouts/docs.html
- css/404.scss
404 page supports redirecting to sensible docs locations.
Closes #17
> Added preliminary custom 404 page.

- css/main.scss
> Tweaks to styles to fix various header layout issues

- index.html
> Remove CTA with no link

- _config.yml
> Add plugin to allow pages to serve as redirects

- _layouts/default.html
> Update Twitter description in meta tag

- _includes/footer.html
- _includes/header.html
- css/404.scss
- css/docs.scss
- css/index.scss
- css/main.scss
The options being used for the vscode autoprefixer plugin is:
```
"autoprefixer.options": {
"overrideBrowserslist": [
"last 2 versions",
"> 0.1%",
"not dead",
"IE 10"
]
},
```
Resolves #54
Rendered Screenshot:
> Update scss files based on autoprefixer and add LF copyright footer

- _includes/footer.html
- css/main.scss
Signed-off-by: Steven Rathbauer <steven@rathpc.com>
> Adding Crossplane Authors to footer

- _includes/hubspot.html
- _layouts/default.html
- _layouts/docs.html
Resolves https://github.com/upbound/upbound-frontend/issues/1751
> Add Hubspot tracking code across site and docs

- _includes/footer.html
- _includes/js/anchor.js
> Render jump links for subsection headers in docs

- _includes/header.html
- css/main.scss
- js/slack-popup.js
> Add banner to prompt users to participate in Slack survey

- _includes/header.html
> Temporarily remove survey

- _includes/header.html
> Re-enable banner

- index.html
> Update text to clarify sandbox project status

- _includes/google-analytics.html
Following the docs to upgrade without having to change the existing code setup: https://support.google.com/analytics/answer/9744165?hl=en
> Upgrae to Google Analytics 4

- js/slack-popup.js
> Additional keyboard accessibility for Slack popup

- _includes/header.html
Signed-off-by: Michael Goff <thephred@gmail.com>
> Update header banner to invite users to the Crossplane Community Day.

- README.md
@thephred showed me this neat way to easily live preview and share changes to the site when they are still in a fork, so I thought it would be useful to add to the readme for others.
> readme: instructions for how to live preview changes to this repo

- _includes/header.html
> Remove banner promoting Community Day

- _includes/header.html
- css/main.scss
> Promote CFP for upcoming Community Day

- _includes/header.html
> Update date in promo banner

- _includes/header.html
> Update banner copy for v1.1 announcement

- _includes/header.html
- css/main.scss
> Update banner to promote Community Day Europe

- _includes/header.html
> Change promo banner content

- _includes/header.html
- css/main.scss
> Update promo banner content - Merge after noon on May 4th

- _includes/header.html
> Update promo banner content

- _includes/values.inc
- _layouts/docs.html
Signed-off-by: Muvaffak Onus <me@muvaf.com>
> use v1.4 as the latest version

- _includes/values.inc
- _layouts/docs.html
See https://github.com/crossplane/crossplane/issues/2764
> Use release-1.6 branch as latest docs

- _includes/header.html
> Update header banner for terrajet announcement

- _includes/values.inc
- _layouts/docs.html
See https://github.com/crossplane/crossplane/issues/2977
> Use Crossplane v1.7 as latest

- _includes/values.inc
- _layouts/docs.html
As part of the v1.8 release, tracking issue https://github.com/crossplane/crossplane/issues/3088.
Previous example #136
> Update latest docs to v1.8

- _includes/values.inc
- _layouts/docs.html
Part of https://github.com/crossplane/crossplane/issues/3169
> Pin latest docs to v1.9

- content/docs/_index.md
- themes/crossplane/layouts/partials/top-nav.html
> Update top nav link to docs

- .github/workflows/hugo.yml
- .gitignore
- Makefile
Adds a run target for local development.
Adds build and validation targets and automatically installs correct
version of hugo for consumers.
> Expand functionality for local development and validation

- themes/crossplane/layouts/partials/docs/versions-dropdown-selector.html
> Fix version drop down by sorting version strings instead of floats

- config.yaml
Updates latest release version to v1.10.
> Bump latest release version to v1.10

- themes/geekboot/assets/scss/_sidebar.scss
> Makes left-hand nav sticky. 

- themes/geekboot/layouts/partials/footer.html
Fixes crossplane/crossplane [issue #3517](https://github.com/crossplane/crossplane/issues/3517)
> Add incubating to CNCF label

- themes/geekboot/assets/scss/_navbar.scss
> Fix spacing when browser size is below 1200px wide. Fixes #227

- themes/geekboot/assets/scss/_survey.scss
- themes/geekboot/assets/scss/docs.scss
- themes/geekboot/layouts/_default/list.html
- themes/geekboot/layouts/partials/survey.html
Adds a banner to the latest landing page asking to take the docs survey
> Add a survey banner

- .gitignore
> Add Zone.Identifier. Resolves #239

- content/master/getting-started/create-configuration.md
- content/v1.10/getting-started/create-configuration.md
- content/v1.10/getting-started/install-configure.md
Updates all v1.10.1 references to v1.10.2.
xref https://github.com/crossplane/crossplane/issues/3595
> Update v1.10 patch versions to v1.10.2

- content/master/reference/composition.md
Docs for https://github.com/crossplane/crossplane/pull/3498
> docs(transform): Add docs for hash transform

- content/master/reference/composition.md
Docs for https://github.com/crossplane/crossplane/pull/3316/files
> docs(compositions): Add docs for quantity transform

- config.yaml
- netlify.toml
Disable `writeStats` by default and add a `sed` replace to enable it for Netlify builds.
> Improve Build Speed

- content/v1.11/concepts/composition.md
> Fix EnvironmentConfigs Selector

- themes/geekboot/layouts/partials/social.html
> add conditionals based on product type

- content/v1.11/concepts/managed-resources.md
Signed-off-by: Jean du Plessis <jean@upbound.io>
Fixes #347
> Fix broken link to api reference

- content/v1.11/getting-started/introduction.md
- content/v1.11/getting-started/provider-aws-part-2.md
- content/v1.11/getting-started/provider-aws-part-3.md
- content/v1.11/getting-started/provider-aws.md
- content/v1.11/getting-started/provider-gcp.md
Fixes https://github.com/crossplane/docs/issues/313
I didn't get a chance to review https://github.com/crossplane/docs/pull/271 very deeply. I spent some time this afternoon reviewing some of the new content. This PR contains a series of small tweaks. It may make sense to review at a commit-by-commit level. Some commit messages have context around why I'm proposing the changes.
> Retroactive review of #271

- content/v1.10/reference/troubleshoot.md
- content/v1.11/getting-started/provider-aws-part-2.md
- content/v1.11/getting-started/provider-aws-part-3.md
- content/v1.11/getting-started/provider-aws.md
Updates the AWS quickstart to ensure consistency after #326''
Resolves #356 
> Fix AWS quickstart bugs

- content/master/concepts/composition.md
- content/v1.10/reference/composition.md
- content/v1.11/concepts/composition.md
Fixes #362 by adding quotes around the annotation value
> Add quotes around annotation value

- content/knowledge-base/guides/multi-tenant.md
Resolves #371 
Vale CI failure is expected.
> remove outdated reference to service catalog

- content/v1.10/getting-started/create-configuration.md
> fix: minor typo

- content/master/concepts/composition.md
Feature implemented in this PR: https://github.com/crossplane/crossplane/pull/3919
> `match` transform: Document the `fallbackTo` option

- content/master/concepts/composition.md
Feature added in this PR: https://github.com/crossplane/crossplane/pull/3917
> Math Transforms: Document `ClampMin` and `ClampMax`

- content/master/software/install.md
> document feature flags available

- content/knowledge-base/integrations/vault-as-secret-store.md
- utils/vale/styles/Crossplane/spelling-exceptions.txt
- utils/vale/styles/Google/Headings.yml
- utils/vale/styles/Microsoft/Terms.yml
- utils/vale/styles/gitlab/Uppercase.yml
This PR updates existing Vault as an ESS guide with plugin change.
> Update vault-as-secret-store.md with plugin changes

- content/master/concepts/composition.md
Add documentation for defaultCompositeDeletePolicy and defaultCompositionUpdatePolicy
Fixes #410
> Add documentation for new defaults

- content/master/concepts/providers.md
- utils/vale/styles/Crossplane/spelling-exceptions.txt
- utils/vale/styles/alex/ProfanityUnlikely.yml
Major update to the Providers "concepts' chapter. 
"Resolves" #336 by pointing to the Provider contrib instructions.
Partially resolves #235 by detailing the possible provider conditions.
Resolves #278 by adding Provider upgrade instructions.
> Concepts: Provider rewrite

- content/master/concepts/composition.md
- content/v1.11/concepts/composition.md
- content/v1.12/concepts/composition.md
I believe slash symbol is extra there
> feat: fix typo in concepts doc

- content/v1.10/concepts/providers.md
- content/v1.11/concepts/providers.md
- content/v1.12/concepts/providers.md
backport PR #420 to releases .10, .11, .12
> Backport Providers update to release versions

- themes/geekboot/assets/scss/_home.scss
- themes/geekboot/layouts/_default/home.html
Adds a search button to the index/home page. Resolves #419
> add search to the home page. 

- content/master/concepts/pods.md
- content/v1.11/concepts/pods.md
- content/v1.12/concepts/pods.md
- utils/vale/styles/Crossplane/spelling-exceptions.txt
- utils/vale/styles/Google/Headings.yml
- utils/vale/styles/Google/WordList.yml
- utils/vale/styles/Microsoft/HeadingAcronyms.yml
Creates a new concept page covering the crossplane core pod and rbac manager pod.
> New page on crossplane pods

- content/master/software/install.md
- content/v1.11/software/install.md
- content/v1.12/software/install.md
- utils/vale/styles/Crossplane/spelling-exceptions.txt
> Update helm chart options for install pages

- content/contribute/code-style-guide.md
- content/master/getting-started/provider-gcp-part-2.md
- content/master/getting-started/provider-gcp-part-3.md
- content/master/getting-started/provider-gcp.md
- content/v1.11/getting-started/provider-aws-part-2.md
- content/v1.11/getting-started/provider-aws-part-3.md
- content/v1.11/getting-started/provider-aws.md
- content/v1.11/getting-started/provider-gcp-part-2.md
- content/v1.11/getting-started/provider-gcp-part-3.md
- content/v1.11/getting-started/provider-gcp.md
- content/v1.12/getting-started/provider-gcp-part-2.md
- content/v1.12/getting-started/provider-gcp-part-3.md
- content/v1.12/getting-started/provider-gcp.md
- themes/geekboot/layouts/shortcodes/editCode.html
Updates the use of the `editCode` marker. Resolves #370 
> Update editCode marker to $@

- content/master/concepts/providers.md
- content/v1.11/concepts/providers.md
- content/v1.12/concepts/providers.md
Adds a bit more context to the Provider Conditions and puts the descriptions above the output.
> Add more details and organize provider Conditions

- content/contribute/contribute.md
> Fixed broken Hugo URL in Getting Started page

- content/v1.12/getting-started/provider-aws-part-3.md
linked to issue #486 
updated broken link to Provider CRD reference to https://doc.crds.dev/github.com/crossplane/provider-aws
> updated link to crd reference

- content/master/concepts/pods.md
- content/v1.11/concepts/pods.md
- content/v1.12/concepts/pods.md
remove a leading - for `poll-interval`
> fix(docs): fix poll-interval -

- content/master/concepts/managed-resources.md
- content/v1.11/concepts/managed-resources.md
- content/v1.12/concepts/managed-resources.md
fix(deletionPolicy): fix correct capital
```
deletionPolicy: delete
deletionPolicy: orphan
```
changed to:
```
deletionPolicy: Delete
deletionPolicy: Orphan
```
> fix(deletionPolicy): fix correct capital

- themes/geekboot/assets/scss/_code-theme-base.scss
- themes/geekboot/assets/scss/_code-theme-dark.scss
- themes/geekboot/assets/scss/_code-theme-light.scss
- themes/geekboot/assets/scss/_content.scss
- themes/geekboot/assets/scss/_hints.scss
- themes/geekboot/assets/scss/_sidebar.scss
- themes/geekboot/assets/scss/_variables.scss
- themes/geekboot/assets/scss/dark-mode.scss
- themes/geekboot/assets/scss/light-mode.scss
- Added new global color variables
- Applied new global colors to backgrounds, typography, navigations, components
- Update code block style and theming. Refactored for easier future color changing
- Improve Tips/Hints/etc structure and theming
> Improve Crossplane Doc Styling

- content/master/concepts/patch-and-transform.md
- utils/vale/styles/Crossplane/crossplane-words.txt
Add new transform from upstream PR https://github.com/crossplane/crossplane/pull/4417.
> add doc for adler32 transform

- content/master/getting-started/provider-gcp-part-2.md
- content/master/getting-started/provider-gcp.md
- content/v1.13/getting-started/provider-gcp-part-2.md
- content/v1.13/getting-started/provider-gcp.md
#530 
Also updated `kubectl get provider` output to show `provider-gcp-pubsub` provider as healthy just to avoid any possible confusion.
> Update provider version and fix azure typo

- content/master/concepts/patch-and-transform.md
Add `FromJson` to the list of supported convert transforms, introduced in https://github.com/crossplane/crossplane/pull/4524
> Add support for FromJson convert transform

- content/master/concepts/patch-and-transform.md
Documentation PR for https://github.com/crossplane/crossplane/pull/4524
Reverting previously merged PR: https://github.com/crossplane/docs/pull/539
> Add support for convert from json to object/list

- content/master/getting-started/provider-aws-part-2.md
Addresses #550 
Updated the DB & Bucket Composition to reflect the correct `spec.location` value.
> Updates AWS get started composition

- content/v1.13/getting-started/provider-aws-part-2.md
> update v1.13 get started

- content/master/getting-started/introduction.md
> Remove trailing underscore from Composition note

- content/master/concepts/pods.md
- content/master/software/install.md
Fixes https://github.com/crossplane/docs/issues/588.
> Document realtime compositions

- content/master/concepts/compositions.md
- content/master/software/install.md
- content/v1.13/concepts/compositions.md
- content/v1.14/concepts/compositions.md
Now that https://github.com/crossplane/crossplane/pull/4814 was merged we should update the docs.
> feat: beta composition schema aware validation

- content/master/concepts/managed-resources.md
- content/master/concepts/pods.md
- content/master/concepts/providers.md
- content/master/getting-started/introduction.md
- content/master/software/install.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
- utils/vale/styles/Crossplane/crossplane-words.txt
Document the feature introduced in https://github.com/crossplane/crossplane/pull/4744
> Document Deployment Runtime Config

- content/v1.14/crds/_index.md
- themes/geekboot/layouts/partials/crds.html
Adds support for deep linking in the API docs
> support collapse/expand links

- themes/geekboot/assets/scss/_crds.scss
Tested on Chrome, Firefox and Safari.
https://github.com/crossplane/docs/assets/3732779/a96cf45b-2d0e-4f15-871c-acdc72b2cca6
> Add vertical bars to expanded rows

- content/v1.14/release-notes/1.14.1.md
- content/v1.14/release-notes/1.14.2.md
- themes/geekboot/layouts/partials/single-list.html
- utils/vale/styles/Crossplane/allowed-jargon.txt
- utils/vale/styles/Crossplane/brands.txt
Release notes for last two minor releases.
> Release Notes for 14.1 and 14.2

- content/knowledge-base/guides/import-existing-resources.md
> fix(examples): fix import examples

- themes/geekboot/assets/scss/_crds.scss
- themes/geekboot/layouts/partials/crds.html
Full mobile support. 
Handle large CRD names
> Mobile support

- content/knowledge-base/integrations/argo-cd-crossplane.md
- Fix new line in paragraphs
- Add sections
- Add context
> Argo CD Improvements

- content/v1.14/api/yaml/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
- content/v1.14/api/yaml/apiextensions.crossplane.io_compositionrevisions.yaml
- content/v1.14/api/yaml/apiextensions.crossplane.io_compositions.yaml
Updates the CRD definitions to v1.14.4
> update APIs to v1.14.4

- themes/geekboot/assets/scss/dark-mode.scss
Addresses https://github.com/upbound/docs/issues/285
> Dark Mode Table Legibility 

- content/knowledge-base/guides/write-a-composition-function-in-go.md
- content/knowledge-base/guides/write-a-composition-function-in-python.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
The end result should be the same function as the Go guide, but Python!
Fixes https://github.com/crossplane/function-sdk-python/issues/11
Fixes https://github.com/crossplane/docs/issues/606
> Add a guide to writing a composition function in Python

- content/master/cli/command-reference.md
- utils/vale/styles/Crossplane/crossplane-words.txt
Add `crossplane beta convert` docs.
Fixes: #682
> add Crossplane CLI convert ref docs

- content/master/cli/command-reference.md
Closes https://github.com/crossplane/docs/pull/695.
Fixes #683.
Just to fix the DCO issue there.
> Add '--include-full-xr' flag to the render subcommand 

- content/master/cli/command-reference.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
- utils/vale/styles/Crossplane/spelling-exceptions.txt
Closes https://github.com/crossplane/docs/issues/684
> validate-command: CLI reference documentation

- content/master/concepts/composition-functions.md
- content/v1.14/concepts/composition-functions.md
- content/v1.15/concepts/composition-functions.md
> fix 'when a you' typo. resolves #729

- content/knowledge-base/integrations/argo-cd-crossplane.md
Add missing conditional from `providerConfig.aws.crossplane.io` status
Fixes: https://github.com/crossplane/docs/issues/665#issue-2057871413
> fix: add missing conditional for ignore Diffs

- content/master/concepts/_index.md
- content/v1.14/concepts/_index.md
- content/v1.15/concepts/_index.md
Hi, I've noticed a duplicate in the concepts and removed the last one.
> Remove duplicated "Composition Functions" concept

- themes/geekboot/layouts/partials/sidebar/roadmap.html
Updates the roadmap link per https://github.com/crossplane/crossplane/pull/5546/files
> Update roadmap link

- content/master/getting-started/install-crossplane-include.md
- content/master/software/install.md
- content/v1.15/getting-started/install-crossplane-include.md
- content/v1.15/software/install.md
Updated docs for https://github.com/crossplane/crossplane/pull/5586
> Add documentation for function deployment via Crossplane Helm Chart

- content/v1.19/concepts/server-side-apply.md
This PR updates the Server-Side Apply documentation for beta promotion in crossplane 1.19. See: https://github.com/crossplane/docs/pull/858#issuecomment-2735674605
> Update server-side apply documentation with beta promotion

- content/v2.0-preview/get-started/get-started-with-composition.md
- content/v2.0-preview/get-started/get-started-with-managed-resources.md
- content/v2.0-preview/whats-crossplane/_index.md
- utils/vale/styles/Crossplane/allowed-jargon.txt
- utils/vale/styles/Crossplane/crossplane-words.txt
The goal of this guide is to:
* Introduce composition as a standalone concept (i.e. no MRs needed)
* Showcase a namespaced composition
* Showcase some different composition functions - i.e. different config language options
I'm also taking a different approach to the previous getting started guides, in that I'm leaving out a lot of explanation of what things are. Instead I'm prioritizing having folks apply things (even if they don't fully understand them) and seeing the results. I feel more detailed explanations should come after the get started guides - e.g. in the concepts section.
> [v2] Add a new 'Get Started With Composition' guide

- content/v2.0-preview/_index.md
- content/v2.0-preview/get-started/_index.md
- content/v2.0-preview/get-started/get-started-with-managed-resources.md
- content/v2.0-preview/whats-new/_index.md
- utils/vale/styles/Crossplane/Spelling.yml
- utils/vale/styles/Crossplane/allowed-jargon.txt
- utils/vale/styles/Crossplane/brands.txt
- utils/vale/styles/Crossplane/provider-words.txt
This page is targeted at folks who're already familiar with v1.x and just want to know what's new.
> Add "What's new in v2.0?" page

- content/v2.0-preview/get-started/install.md
This is the latest preview release.
> Pin preview docs to v2.0.0-preview.1

- content/master/cli/_index.md
Related to https://github.com/crossplane/crossplane/pull/6119
> Add autocompletion for CLI docs

- content/master/whats-new/_index.md
- content/v2.0/whats-new/_index.md
> Update _index.md nit
